### ISSUE TITLE
Etablishment of ATIS

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#102]
ENRS -  ATIS AVAILABLE ON FREQUENCY 129.900 MHZ
FROM: Thu 30 Jun 2022 11:35 TO: Thu 06 Oct 2022 00:00

ENRM -  ATIS ESTABLISHED, CALLSIGN: ROERVIK INFORMATION, FREQ: 132.025MHZ, HR: HO REF AD 2
ENRM 2.18
FROM: Thu 08 Sep 2022 16:30 TO: Thu 01 Dec 2022 00:00

ENNM - NEW ATIS FREQ 133.200 MHZ REF AIP ENNM AD 2 EFF 11 AUG 2022
FROM: Wed 07 Sep 2022 07:21 TO: PERM

ENMH - ATIS MEHAMN INFORMATION AVAILABLE ON FREQ 132,150 MHZ
FROM: Thu 15 Sep 2022 10:26 TO: Wed 05 Oct 2022 23:59

ENBV - ATIS AVAILABLE ON FREQUENCY 132.675 MHZ
FROM: Thu 30 Jun 2022 10:49 TO: Thu 06 Oct 2022 22:00

ENSS - ATIS AVAILABLE ON FREQUENCY 127.42500 MHZ
FROM: Wed 06 Jul 2022 14:03 TO: Wed 05 Oct 2022 23:59

ENHK (AIP AMDT) - Freq 132.300

**Comment by Adrian2k** [comment]
@marud94 fikser du vatatis?

**Comment by Adrian2k** [comment]
RNP som default approach

RNP-Z som default på ENSS 33

**Comment by marud94** [comment]
> @marud94 fikser du vatatis?

Fixed.
