### ISSUE TITLE
Implementing VCH?

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#104]
https://github.com/DrFreas/VCH/releases
Jannik har vist meg denne. Denne ser ut som kan være nyttefull for oss under busy omstendigheter. Dere kan jo ta en titt @Adrian2k og @morettio og se om dere tror denne er useful i sektorfila vår. Kan jo eventuelt være loadet og ligger tilgjengelig men hidden i våre lister.

Legger med et bidlde fra Jannik som illustrerer hvordan det ser ut. Kan kan sikkert svare for ting om dere lurer på brukeropplevelsen.
![image](https://user-images.githubusercontent.com/79529337/193508594-ccbfd15e-ef4c-4ec5-b43d-6977508a3f1c.png)

**Comment by Adrian2k** [comment]
Prøver å være veldig forsiktig med å legge inn plugins da plugins er kjent for å skape CTD i EuroScope.
Akkurat her så kan man jo bruke scratchpad til dette, slik vi har gjort i alle år?

**Comment by morettio** [comment]
Jeg ser ikke nytten i å ha dette i sectorfila vår. Nå legger vi inn CDM så får vi evt ta dette senere?

**Comment by krislarsen** [comment]
> Jeg ser ikke nytten i å ha dette i sectorfila vår. Nå legger vi inn CDM så får vi evt ta dette senere?

Støtter dette, setter den on hold og en ny vurdering neste år.
