### ISSUE TITLE
ENGM stand areas, as opposed to stand radius

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#108]
![image](https://user-images.githubusercontent.com/17087998/194717849-fb447bd6-1125-481a-8be7-d1198d0f34f4.png)
Alot of aircraft at GM spawn just outside the circle. Think its because stands are placed at nose possition, and euroscope reports aircraft at middle possition.

**Comment by meltinglava** [comment]
ref #89

**Comment by krislarsen** [comment]
Kan være en god idé å å gjøre det til polygon-stand. Mulig det blir bedre nøyaktighet med ny scenery til MSFS, men de gamle add-onsene kommer til å bli stående uansett. @Adrian2k fikset dette sist, så det får bli opp til han

**Comment by Adrian2k** [comment]
Det er så mange stands..

**Comment by meltinglava** [comment]
Det vi kan prøve er å flytte alle sirklene en (halv eller en tredjedels) stand størrelse bakover. Ettersom at jeg tror at vi aldri vil se noen fly på fremre halvdel av sirkelen.

**Comment by krislarsen** [comment]
> Det vi kan prøve er å flytte alle sirklene en (halv eller en tredjedels) stand størrelse bakover. Ettersom at jeg tror at vi aldri vil se noen fly på fremre halvdel av sirkelen.

Tror det ikke er aktuelt å flytte posisjonene. Disse er basert på riktige koordinater. Mulig sirklene kan økes en smule, må sees an i så fall hvor mye som kan økes

**Comment by marud94** [comment]
@Adrian2k Om du blir med meg neste gang jeg skal jobbe natt (om 3 uker) kan jeg hjelpe til med å se på det.

**Comment by Adrian2k** [comment]
@meltinglava du får polygons på pir-nord for det er kun der jeg antar problemet er (pga offset aerosoft scenery).

![image](https://user-images.githubusercontent.com/35482228/207592139-3d2470ff-9748-4f89-b4d5-160b05515bda.png)


Stand 77 til 89 er ikke gjort, fordi satelittkartet er slikt i det området, samt at det er egentlig ingen god måte å tegne overlappene stands på.
![image](https://user-images.githubusercontent.com/35482228/207592508-e784af58-34c3-48d2-9506-f65b57cf6217.png)

**Comment by Adrian2k** [comment]
@meltinglava du får teste ut det som ligger ute i repoen nå

**Comment by Adrian2k** [comment]
Antar at denne er løst siden jeg ikke har hørt noe mer fra saken
