### ISSUE TITLE
New Coordinates for E6

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#109]
N060.23.53.284 E011.13.49.405 N060.23.11.450 E011.12.46.239  
  N060.23.11.450 E011.12.46.239 N060.23.11.450 E011.12.46.239  
  N060.23.11.450 E011.12.46.239 N060.21.59.157 E011.12.13.804  
  N060.21.59.157 E011.12.13.804 N060.21.59.157 E011.12.13.804  
  N060.21.59.157 E011.12.13.804 N060.21.08.540 E011.12.28.904  
  N060.21.08.540 E011.12.28.904 N060.21.08.540 E011.12.28.904  
  N060.21.08.540 E011.12.28.904 N060.20.45.854 E011.12.29.181  
  N060.20.45.854 E011.12.29.181 N060.20.45.854 E011.12.29.181  
  N060.20.45.854 E011.12.29.181 N060.19.54.087 E011.11.22.784  
  N060.19.54.087 E011.11.22.784 N060.19.54.087 E011.11.22.784  
  N060.19.54.087 E011.11.22.784 N060.19.42.522 E011.11.12.228  
  N060.19.42.522 E011.11.12.228 N060.19.42.522 E011.11.12.228  
  N060.19.42.522 E011.11.12.228 N060.19.30.092 E011.10.44.606  
  N060.19.30.092 E011.10.44.606 N060.19.30.092 E011.10.44.606  
  N060.19.30.092 E011.10.44.606 N060.19.25.430 E011.10.34.563  
  N060.19.25.430 E011.10.34.563 N060.19.25.430 E011.10.34.563  
  N060.19.25.430 E011.10.34.563 N060.19.27.942 E011.10.40.244  
  N060.19.27.942 E011.10.40.244 N060.19.27.942 E011.10.40.244  
  N060.19.27.942 E011.10.40.244 N060.19.16.811 E011.10.09.220  
  N060.19.16.811 E011.10.09.220 N060.19.16.811 E011.10.09.220  
  N060.19.16.811 E011.10.09.220 N060.19.12.837 E011.09.47.015  
  N060.19.12.837 E011.09.47.015 N060.19.12.837 E011.09.47.015  
  N060.19.12.837 E011.09.47.015 N060.19.10.249 E011.09.26.677  
  N060.19.10.249 E011.09.26.677 N060.19.10.249 E011.09.26.677  
  N060.19.10.249 E011.09.26.677 N060.19.07.568 E011.09.13.803  
  N060.19.07.568 E011.09.13.803 N060.19.07.568 E011.09.13.803  
  N060.19.07.568 E011.09.13.803 N060.18.48.442 E011.08.40.771  
  N060.18.48.442 E011.08.40.771 N060.18.48.442 E011.08.40.771  
  N060.18.48.442 E011.08.40.771 N060.18.38.093 E011.08.31.072  
  N060.18.38.093 E011.08.31.072 N060.18.38.093 E011.08.31.072  
  N060.18.38.093 E011.08.31.072 N060.18.28.265 E011.08.28.237  
  N060.18.28.265 E011.08.28.237 N060.18.28.265 E011.08.28.237  
  N060.18.28.265 E011.08.28.237 N060.18.18.485 E011.08.28.017  
  N060.18.18.485 E011.08.28.017 N060.18.18.485 E011.08.28.017  
  N060.18.18.485 E011.08.28.017 N060.18.06.176 E011.08.20.256  
  N060.18.06.176 E011.08.20.256 N060.18.06.176 E011.08.20.256  
  N060.18.06.176 E011.08.20.256 N060.17.39.446 E011.08.10.258  
  N060.17.39.446 E011.08.10.258 N060.17.39.446 E011.08.10.258  
  N060.17.39.446 E011.08.10.258 N060.17.18.335 E011.08.00.501  
  N060.17.18.335 E011.08.00.501 N060.17.18.335 E011.08.00.501  
  N060.17.18.335 E011.08.00.501 N060.17.06.791 E011.08.09.154  
  N060.17.06.791 E011.08.09.154 N060.17.06.791 E011.08.09.154  
  N060.17.06.791 E011.08.09.154 N060.16.51.948 E011.08.38.211  
  N060.16.51.948 E011.08.38.211 N060.16.51.948 E011.08.38.211  
  N060.16.51.948 E011.08.38.211 N060.16.51.299 E011.08.40.743  
  N060.16.51.299 E011.08.40.743 N060.16.51.299 E011.08.40.743  
  N060.16.51.299 E011.08.40.743 N060.16.28.899 E011.09.02.388  
  N060.16.28.899 E011.09.02.388 N060.16.28.899 E011.09.02.388  
  N060.16.28.899 E011.09.02.388 N060.16.19.410 E011.09.13.051  
  N060.16.19.410 E011.09.13.051 N060.16.19.410 E011.09.13.051  
  N060.16.19.410 E011.09.13.051 N060.16.05.820 E011.09.48.030  
  N060.16.05.820 E011.09.48.030 N060.16.05.820 E011.09.48.030  
  N060.16.05.820 E011.09.48.030 N060.15.39.858 E011.10.26.829  
  N060.15.39.858 E011.10.26.829 N060.15.39.858 E011.10.26.829  
  N060.15.39.858 E011.10.26.829 N060.15.15.606 E011.10.50.331  
  N060.15.15.606 E011.10.50.331 N060.15.15.606 E011.10.50.331  
  N060.15.15.606 E011.10.50.331 N060.14.58.945 E011.10.57.040  
  N060.14.58.945 E011.10.57.040 N060.14.58.945 E011.10.57.040  
  N060.14.58.945 E011.10.57.040 N060.14.45.986 E011.10.56.289  
  N060.14.45.986 E011.10.56.289 N060.14.45.986 E011.10.56.289  
  N060.14.45.986 E011.10.56.289 N060.14.05.816 E011.10.28.679  
  N060.14.05.816 E011.10.28.679 N060.14.05.816 E011.10.28.679  
  N060.14.05.816 E011.10.28.679 N060.13.44.489 E011.10.24.220  
  N060.13.44.489 E011.10.24.220 N060.13.44.489 E011.10.24.220  
  N060.13.44.489 E011.10.24.220 N060.13.16.672 E011.10.45.497  
  N060.13.16.672 E011.10.45.497 N060.13.16.672 E011.10.45.497  
  N060.13.16.672 E011.10.45.497 N060.12.30.879 E011.11.09.374  
  N060.12.30.879 E011.11.09.374 N060.12.30.879 E011.11.09.374  
  N060.12.30.879 E011.11.09.374 N060.11.44.327 E011.11.23.181  
  N060.11.44.327 E011.11.23.181 N060.11.44.327 E011.11.23.181  
  N060.11.44.327 E011.11.23.181 N060.11.31.523 E011.11.21.316  
  N060.11.31.523 E011.11.21.316 N060.11.31.523 E011.11.21.316  
  N060.11.31.523 E011.11.21.316 N060.11.10.563 E011.10.59.302  
  N060.11.10.563 E011.10.59.302 N060.11.10.563 E011.10.59.302  
  N060.11.10.563 E011.10.59.302 N060.10.54.609 E011.10.29.087  
  N060.10.54.609 E011.10.29.087 N060.10.54.609 E011.10.29.087  
  N060.10.54.609 E011.10.29.087 N060.10.51.826 E011.10.22.000  
  N060.10.51.826 E011.10.22.000 N060.10.51.826 E011.10.22.000  
  N060.10.51.826 E011.10.22.000 N060.10.39.238 E011.10.06.754  
  N060.10.39.238 E011.10.06.754 N060.10.39.238 E011.10.06.754  
  N060.10.39.238 E011.10.06.754 N060.09.57.401 E011.09.35.687  
  N060.09.57.401 E011.09.35.687 N060.09.57.401 E011.09.35.687  
  N060.09.57.401 E011.09.35.687 N060.09.19.587 E011.09.00.045  
  N060.09.19.587 E011.09.00.045 N060.09.19.587 E011.09.00.045  
  N060.09.19.587 E011.09.00.045 N060.09.08.660 E011.08.56.916  
  N060.09.08.660 E011.08.56.916 N060.09.08.660 E011.08.56.916  
  N060.09.08.660 E011.08.56.916 N060.08.57.109 E011.08.56.611  
  N060.08.57.109 E011.08.56.611 N060.08.57.109 E011.08.56.611  
  N060.08.57.109 E011.08.56.611 N060.08.28.646 E011.09.16.016  
  N060.08.28.646 E011.09.16.016 N060.08.28.646 E011.09.16.016  
  N060.08.28.646 E011.09.16.016 N060.08.10.370 E011.09.22.301  
  N060.08.10.370 E011.09.22.301 N060.08.10.370 E011.09.22.301  
  N060.08.10.370 E011.09.22.301 N060.07.54.126 E011.09.40.817  
  N060.07.54.126 E011.09.40.817 N060.07.54.126 E011.09.40.817  
  N060.07.54.126 E011.09.40.817 N060.07.42.879 E011.09.50.544  
  N060.07.42.879 E011.09.50.544 N060.07.42.879 E011.09.50.544  
  N060.07.42.879 E011.09.50.544 N060.07.24.581 E011.09.52.100  
  N060.07.24.581 E011.09.52.100 N060.07.24.581 E011.09.52.100  
  N060.07.24.581 E011.09.52.100 N060.07.13.485 E011.09.43.946  
  N060.07.13.485 E011.09.43.946 N060.07.13.485 E011.09.43.946  
  N060.07.13.485 E011.09.43.946 N060.06.39.274 E011.08.57.588  
  N060.06.39.274 E011.08.57.588 N060.06.39.274 E011.08.57.588  
  N060.06.39.274 E011.08.57.588 N060.06.16.400 E011.08.35.500  
  N060.06.16.400 E011.08.35.500 N060.06.16.400 E011.08.35.500  
  N060.06.16.400 E011.08.35.500 N060.05.50.548 E011.08.37.364  
  N060.05.50.548 E011.08.37.364 N060.05.50.548 E011.08.37.364  
  N060.05.50.548 E011.08.37.364 N060.04.07.670 E011.09.14.654  
  N060.04.07.670 E011.09.14.654 N060.04.07.670 E011.09.14.654  
  N060.04.07.670 E011.09.14.654 N060.03.46.069 E011.09.08.685  
  N060.03.46.069 E011.09.08.685 N060.03.46.069 E011.09.08.685  
  N060.03.46.069 E011.09.08.685 N060.03.19.624 E011.08.37.725  
  N060.03.19.624 E011.08.37.725 N060.03.19.624 E011.08.37.725  
  N060.03.19.624 E011.08.37.725 N060.02.59.882 E011.08.13.114  
  N060.02.59.882 E011.08.13.114 N060.02.59.882 E011.08.13.114  
  N060.02.59.882 E011.08.13.114 N060.02.17.763 E011.06.31.594  
  N060.02.17.763 E011.06.31.594 N060.02.17.763 E011.06.31.594  
  N060.02.17.763 E011.06.31.594 N060.02.05.454 E011.06.05.457  
  N060.02.05.454 E011.06.05.457 N060.02.05.454 E011.06.05.457  
  N060.02.05.454 E011.06.05.457 N060.01.45.886 E011.05.45.697  
  N060.01.45.886 E011.05.45.697 N060.01.45.886 E011.05.45.697  
  N060.01.45.886 E011.05.45.697 N060.01.37.386 E011.05.26.118  
  N060.01.37.386 E011.05.26.118 N060.01.37.386 E011.05.26.118  
  N060.01.37.386 E011.05.26.118 N060.01.28.027 E011.04.33.843  
  N060.01.28.027 E011.04.33.843 N060.01.28.027 E011.04.33.843  
  N060.01.28.027 E011.04.33.843 N060.01.19.227 E011.04.13.151  
  N060.01.19.227 E011.04.13.151 N060.01.19.227 E011.04.13.151  
  N060.01.19.227 E011.04.13.151 N060.00.53.523 E011.03.57.505  
  N060.00.53.523 E011.03.57.505 N060.00.53.523 E011.03.57.505  
  N060.00.53.523 E011.03.57.505 N060.00.42.405 E011.03.42.733  
  N060.00.42.405 E011.03.42.733 N060.00.42.405 E011.03.42.733  
  N060.00.42.405 E011.03.42.733 N060.00.37.925 E011.03.30.377  
  N060.00.37.925 E011.03.30.377 N060.00.37.925 E011.03.30.377  
  N060.00.37.925 E011.03.30.377 N060.00.27.265 E011.03.01.033  
  N060.00.27.265 E011.03.01.033 N060.00.27.265 E011.03.01.033  
  N060.00.27.265 E011.03.01.033 N060.00.07.803 E011.02.44.057  
  N060.00.07.803 E011.02.44.057 N060.00.07.803 E011.02.44.057  
  N060.00.07.803 E011.02.44.057 N059.59.59.454 E011.02.36.302  
  N059.59.59.454 E011.02.36.302 N059.59.59.454 E011.02.36.302  
  N059.59.59.454 E011.02.36.302 N059.59.21.435 E011.01.41.659  
  N059.59.21.435 E011.01.41.659 N059.59.21.435 E011.01.41.659  
  N059.59.21.435 E011.01.41.659 N059.59.16.643 E011.01.33.943  
  N059.59.16.643 E011.01.33.943 N059.59.16.643 E011.01.33.943  
  N059.59.16.643 E011.01.33.943 N059.59.07.556 E011.00.24.726  
  N059.59.07.556 E011.00.24.726 N059.59.07.556 E011.00.24.726  
  N059.59.07.556 E011.00.24.726 N059.58.49.896 E010.59.42.498  
  N059.58.49.896 E010.59.42.498 N059.58.49.896 E010.59.42.498  
  N059.58.49.896 E010.59.42.498 N059.58.08.889 E010.59.19.340  
  N059.58.08.889 E010.59.19.340 N059.58.08.889 E010.59.19.340  
  N059.58.08.889 E010.59.19.340 N059.57.51.227 E010.58.55.858  
  N059.57.51.227 E010.58.55.858 N059.57.43.160 E010.58.28.844  
  N059.57.43.160 E010.58.28.844 N059.57.36.377 E010.58.16.823  
  N059.57.36.377 E010.58.16.823 N059.57.17.342 E010.57.33.143  
  N059.57.17.342 E010.57.33.143 N059.57.14.772 E010.57.28.522  
  N059.57.14.772 E010.57.28.522 N059.57.00.200 E010.57.10.077  
  N059.57.00.200 E010.57.10.077 N059.56.49.068 E010.56.29.566  
  N059.56.49.068 E010.56.29.566 N059.56.29.530 E010.56.12.649  
  N059.56.29.530 E010.56.12.649 N059.56.22.835 E010.55.56.743  
  N059.56.22.835 E010.55.56.743 N059.56.24.686 E010.55.08.852  
  N059.56.24.686 E010.55.08.852 N059.56.22.677 E010.54.19.257  
  N059.56.22.677 E010.54.19.257 N059.55.54.302 E010.52.08.391  
  N059.55.54.302 E010.52.08.391 N059.55.35.752 E010.51.26.811  
  N059.55.35.752 E010.51.26.811 N059.55.26.163 E010.50.31.821  
  N059.55.26.163 E010.50.31.821 N059.55.24.682 E010.49.47.370  

  N060.09.19.587 E011.09.00.040 N060.09.30.338 E011.08.55.917  
  N060.09.30.338 E011.08.55.917 N060.09.37.895 E011.08.44.209  
  N060.09.37.895 E011.08.44.209 N060.09.56.636 E011.07.49.767  
  N060.09.56.636 E011.07.49.767 N060.10.03.935 E011.06.53.324  
  N060.10.03.935 E011.06.53.324 N060.10.15.259 E011.06.10.055  
  N060.10.15.259 E011.06.10.055 N060.10.40.990 E011.05.42.009  
  N060.10.40.990 E011.05.42.009 N060.10.57.833 E011.05.35.238  
  N060.10.57.833 E011.05.35.238 N060.11.19.818 E011.05.44.648

**Comment by morettio** [comment]
Updated to GNG

**Comment by morettio** [comment]
![image](https://user-images.githubusercontent.com/59777657/195671987-b47acd13-2c2e-4cbb-a69f-15a2a13608cd.png)
