### ISSUE TITLE
Stand assignment ENBR

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#119]
![image](https://user-images.githubusercontent.com/79529337/199581010-a2b60eeb-a8d7-4171-beb2-95e23f1b5922.png)
ATYP: B748

**Comment by meltinglava** [comment]
Ingen stands er ARC F på ENBR. Blir fort deice eller stand 1 på disse. Så tror technical er greit nok.

**Comment by krislarsen** [comment]
Da er det bedre å sette opp for Deice eller 1 for det, ikke lille technical
:)


tor. 3. nov. 2022 kl. 07:46 skrev meltinglava ***@***.***>:
