### ISSUE TITLE
Active controller line bug (ENGM_E_TWR)

### ISSUE THREAD

**Issue by janfelhut** [Vatsim-Scandinavia/ENOR-Sectorfile#123]
![image](https://user-images.githubusercontent.com/51382169/200138020-5e13eed9-337a-49b7-94e0-a8f841b34c7d.png)

When siting ENGM_W_TWR and ENOR_S_CTR is online it shows east tower is online...

**Comment by Adrian2k** [comment]
Skjønner ikke hvordan disse bugsa kommer med.
Fixed.

**Comment by janfelhut** [comment]
![image](https://user-images.githubusercontent.com/51382169/200386049-9b2d5cab-7016-43ea-9bbc-526ac0ab6231.png)
Issue appeared again if ENSV is online

**Comment by Adrian2k** [comment]
Som sagt, buggen er fiksa. Vent på neste oppdatering.

**Comment by janfelhut** [comment]
Har den blitt fikset? Får fikk den opp i går. Hadde ENOR_S_CTR på som over og W_GND u der... Ser ut som til å henge igjen
