### ISSUE TITLE
ENGM Heli VRP missing

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#132]
Ref AD 2 ENGM 6 - 2 - HELICOPTER ROUTE CHART

**Comment by morettio** [comment]
Trenger vi denne inn i Maps?

**Comment by Adrian2k** [comment]
Vi har helikopter VRP på ENBR, pluss at du vet aldri når plutselig Jannik skal fly helikopteret sitt på GM.

**Comment by morettio** [comment]
73e932008445a03d777c10b20164ef1d9e1becb4
