### ISSUE TITLE
COPX SOLKA 

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#137]
![EuroScope_fOHlFNN0Na](https://user-images.githubusercontent.com/17087998/206803668-c7b68bec-1743-4825-8689-3be862dcfa90.png)

**Comment by krislarsen** [comment]
Mulig dette er samme bug som #67 . Sjekker dette opp

**Comment by krislarsen** [comment]
Endret på COPXen her. Rekker ikke å få testet ut dette nå, så om noen kan det så hadde det vært supert.

**Comment by marud94** [comment]
@meltinglava Om du får testa og bekrefta dette hadde det vært prima!

**Comment by krislarsen** [comment]
Fikk ikke friskmeldt denne ved test, vet ikke om ACC har guest på ENVA TMA, mulig det løser issuet med SOLKA handoff fra ENBD til ESOS? @Adrian2k

**Comment by Adrian2k** [comment]
Lagt inn guest

**Comment by krislarsen** [comment]
I belive this is solved as I've not heard any more issues related to this. I'll close this for now.
