### ISSUE TITLE
Handover logic oksat with ENOS split, on OKSAT4A.

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#138]
Suggests EN6 until direct oksat is given.

**Comment by Adrian2k** [comment]
The only possible solution is adding a COPX on OKAKI (as COPX FIX) with climb 210, but not sure if it will cause other issues or not.

If that does not work, then there is no possible way of solving the issue, due to EuroScope logic does not allow us to hardcode handover sectors.

**Comment by krislarsen** [comment]
![image](https://user-images.githubusercontent.com/79529337/207586526-936f4878-2660-4d92-b311-ea222d5bb612.png)
Dyttet ut modifikasjon nå. Og som med #137 så må dette testes.

**Comment by krislarsen** [comment]
Testet denne nå. Det er egentlig ingen god måte å løse dette på, men har justert at den er litt mer riktig nå, men det vil fortsatt være feil og foreslå S6 når du gir direct OKSAT på OKSAT4A
