### ISSUE TITLE
Missing "Next Sector MAP"

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#139]
![image](https://user-images.githubusercontent.com/79529337/206872979-fa6b4e55-d355-464e-9a61-ebfdf6df2a1f.png)

ESN (132.150) is missing when connected as ENOS_N_CTR

**Comment by morettio** [comment]
Added to release A2301

**Comment by marud94** [comment]
> Added to release A2301

@morettio ikke A2213 29. Desember altså?

**Comment by morettio** [comment]
Skriveleif
*Jakob Arne Brønstad*

*Tlf: (+47) 986 50 540*


tir. 13. des. 2022 kl. 22:16 skrev Magnus Rudjord ***@***.***
