### ISSUE TITLE
Sector Ownership ENBR_D_APP

### ISSUE THREAD

**Issue by LazyHenrik** [Vatsim-Scandinavia/ENOR-Sectorfile#142]
It appears next sector for ENBR_W_APP is ENSV_CTR when both ENSV_CTR and ENBR_D_APP is online. It also appears that ENBR_D_APP only has Flesland CTR:
![image](https://user-images.githubusercontent.com/56515702/209190375-1e48c2fc-a735-4462-beed-93459e8be5e3.png)
![image](https://user-images.githubusercontent.com/56515702/209190802-82894671-8ba9-4a32-8c63-0cb25308a141.png)

**Comment by krislarsen** [comment]
ENBR_TWR var ikke på, men feilen blir meldt til å være samme med TWR på også. 35 config
