### ISSUE TITLE
COPX OKSAT

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#143]
Får ikke climb FL310, har heller ikke fått FL290 på MASEV. Sitter med siste DEV fil.

![image](https://user-images.githubusercontent.com/35482228/209702768-250bb003-e339-4385-bf83-e0f5ddfd8029.png)

**Comment by krislarsen** [comment]
Vil ikke dukke opp når Sweden ikke er pålogget. ES relatert som jeg ikke får fikset

**Comment by Adrian2k** [comment]
Fikk FL210 på ENTO departures med samme oppsett

**Comment by krislarsen** [comment]
Av en eller annen grunn så har den en COPX som den finner, men det virker som det er feil COPX. 
...
Mulig feilen ligger i sortorder. Har sendt en melding til utvikleren i Sverige så forhåpentligvis får vi fikset det til neste AIRAC.

**Comment by krislarsen** [comment]
Har ikke hørt noe om dette er fortsatt et issue, så stenger denne.
