### ISSUE TITLE
ENSH ATIS

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#148]
Lagt til i GNG.

Fikser du vatatis @marud94?

ENSH_I_TWR
ENRC_CTR
ENBD_CTR
ENBD_E_CTR
ENOR_CTR

RNP-Y på 01.
Egentlig ikke noen approacher for 19, evnt visual?

**Comment by marud94** [comment]
@Adrian2k Skal se på ATIS ila uka. Setter visual på 19, det som er normen irl hvertfall.
