### ISSUE TITLE
COPX LUNIP wrong XFL

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#150]
![image](https://user-images.githubusercontent.com/17087998/210432813-893388bd-70a0-46f4-bc92-f4dbe9c03152.png)
SAS455 in the screenshot

**Comment by Adrian2k** [comment]
Vet ikke hva jeg tenkte med guest controller, men ikke det som er tilfellet her. Flyet er innenfor ENOS sitt luftrom.

**Comment by Adrian2k** [comment]
Hint: Det er REGMA COPX mellom ESMM-ENOS som EuroScope tolker her. Vet ikke hvorfor den kommer inn når ESMM er avlogga.

**Comment by krislarsen** [comment]
> Hint: Det er REGMA COPX mellom ESMM-ENOS som EuroScope tolker her. Vet ikke hvorfor den kommer inn når ESMM er avlogga.
DEVKU COPX er prioritert over REGMA COPXen så dette burde være rett. Eneste jeg kan prøve på er å legge inn en COPX som er fra S3 TOP/Upper uten at jeg vil tro det løser problemet.

**Comment by krislarsen** [comment]
Gjort en småendring i sortorder. Stenger saken som fullført ettersom jeg tror ikke det vil bli en forbedring her.
