### ISSUE TITLE
WTC visible in ES

### ISSUE THREAD

**Issue by marud94** [Vatsim-Scandinavia/ENOR-Sectorfile#155]
Per Meese's recommendation in VATSCA

- [x] Add WTC after ATYP in Departure list
- [x] Make WTC visible on SMR

**Comment by krislarsen** [comment]
Ikke heeeelt sikker enda så vent litt med denne så tenker jeg vi finner en god løsning på det uten at det blir for kluttrete

**Comment by marud94** [comment]
Her er eksempel på hvordan det blir sånn direkte som Meese foreslo
![Skjermbilde 2023-01-16 205054](https://user-images.githubusercontent.com/79376555/212756276-fd7ed438-1465-4024-90e5-4ccf5c9ceefc.png)

Ligger på egen branch så kan endres fortløpende ved behov

**Comment by Adrian2k** [comment]
Ikke merge i main, subject to review.
