### ISSUE TITLE
Add ENOL MVA

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#156]
Add MVA lines for Ørland (ENOL). 
![image](https://user-images.githubusercontent.com/89723211/213235435-b7b6e169-f686-47a8-bdf1-d5983beba3eb.png)

**Comment by Adrian2k** [comment]
Blir for inkomplett. Når jeg kun har bilde på denne måten så må hele TMA'et være med i bildet for at det bli nøyaktig nok for oss. Alle eksisterende MVA tegningene vi har er hentet rett fra reelle kilder med koordinater eller tilsvarende.
Mangler forøverig også en av MVA nivående her.

Ørland er heller ikke kritisk mtp på terreng.

**Comment by Sanderli25** [comment]
New ref image. Will look into it.
