### ISSUE TITLE
CDM version 2.1.0 released

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#158]
https://github.com/rpuig2001/CDM/releases

**Comment by marud94** [comment]
![Skjermbilde 2023-01-27 162503](https://user-images.githubusercontent.com/79376555/215139522-1a004fbf-182d-4bda-b671-d35129ce797b.png)
![Skjermbilde 2023-01-27 162446](https://user-images.githubusercontent.com/79376555/215139526-74e02fd6-39f8-4c5c-b48f-72e61de2182b.png)
![Skjermbilde 2023-01-27 162528](https://user-images.githubusercontent.com/79376555/215139532-ae0e6a49-5392-42f5-aa1e-773860b01b7c.png)
