### ISSUE TITLE
COPX: ENZV dep assumed by ENZV_APP dir ALOTI sets XFL to A020

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#166]
![image](https://user-images.githubusercontent.com/17087998/218825250-363e5a86-bc55-45e3-a6b4-32609efb797b.png)

**Comment by krislarsen** [comment]
Gjerne legg med hele scopet som indikerer hvor flyet er. Dette er nyttefull del i feilsøkingen.

**Comment by meltinglava** [comment]
wilco. Fikk samme 10 NM sør for ZV med direct BAVTA.

**Comment by krislarsen** [comment]
Har sett gjennom GNG og finner ingen relevante COPXer som skal sette XFL til A020. Så får ikke fikset dette. Mulig det er TWR som har gitt annen XFL om det var pålogget på tidspunktet. Uansett, ingenting jeg får gjort
