### ISSUE TITLE
Extended Centerlines GRplugin APP window

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#173]
Change the existing standard extended centerlines in the ground plugin APP window to the "TopSky-ones" to match IRL setup. 

![image](https://user-images.githubusercontent.com/89723211/222283227-bbd5f493-01b5-48ad-a100-da0b86cf5bfa.jpeg)![image](https://user-images.githubusercontent.com/89723211/222283269-919d9ecf-8cb8-4f98-a008-facdaf59aec0.jpeg)![image](https://user-images.githubusercontent.com/89723211/222283294-a3cfd5c1-a515-4d2e-b6ff-57bd5ebcd237.jpeg)

**Comment by Adrian2k** [comment]
> Går utifra at det ikkje er så lett mtp at det ene er GRplugin og det andre Topsky

Samme utvikler, så relativt likt fremgangsmåte.
Jeg får se på det engang jeg gidder.

**Comment by Adrian2k** [comment]
Fixed
