### ISSUE TITLE
Update ground layout ENBR + ENGM

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#174]
I think we should also update the ground layout at ENBR and ENGM after the completion of all the outdated ones. At ENBR we have good images from late 2022 which could be used the create an almost excact replica. At ENGM there are also some good images, which can lead to an even better one. I know that the ground layouts were made as they are because not everyone has towerview, and they want to know where things are, but I dont think all buldings around ENGM is necessary to have in the layout. At ENBR however, it is the opposite on their ground layout. I have started with an idea for both airports, but needs to be tweaked to be perfect. 

![image](https://user-images.githubusercontent.com/89723211/222372785-cf346ebc-01ce-4ef6-a9db-fdac9ff8883c.png)
![image](https://user-images.githubusercontent.com/89723211/222372804-f407cd47-4a2c-413a-b35c-f76f6ae1ad55.png)
![20221025_162741](https://user-images.githubusercontent.com/89723211/222372850-702f3112-2ce6-4c62-97ae-fd0f1fc729c2.jpg)
![20221025_165002](https://user-images.githubusercontent.com/89723211/222372893-fc65ca6e-255c-4e2c-801e-6551323e4afe.jpg)
![image](https://user-images.githubusercontent.com/89723211/222373454-81de75e4-3a37-4cae-b57b-f0fb6f3488b9.png)
![IMG_5625](https://user-images.githubusercontent.com/89723211/222372950-a0b48494-fb78-41c2-8793-99fa837a21bc.PNG)
![1538597902330](https://user-images.githubusercontent.com/89723211/222374089-ecc7cc56-de61-4e7b-87ba-c92f51fd6892.jpg)
![osl_tower](https://user-images.githubusercontent.com/89723211/222372962-1657844a-c9e1-4ec1-b4f0-1b1d7d97f419.png)
![Radar 2022](https://user-images.githubusercontent.com/89723211/222373066-e6f26b3a-fb6b-49a8-9289-e9dc2b022fc5.png)
(Last image from ENGM is from 2022)

**Comment by Adrian2k** [comment]
Dette får være @BlomsenSr sitt valg, han som har laga groundlayoutene.

Men argumentene gir ikke helt mening, at du på Gardermoen synes det er unødvendig med byggnigner/terminal mens på Flesland så vil du ikke bare ha terminalen men også alle jetwayene i full detalj, samt hver minste detalj på gresset.

Bare fordi noe gjøres IRL betyr det ikke at det er den beste løsninga. Groundlayoutene er allerede basert på IRL design, det at detaljnivået er litt annerledes skjønner jeg ikke at det skal lages så mye oppstyr over.

Man må også i ES til en viss grad begrense antall "punkter" man legger inn, hvor mer som ligger inne hvor værre blir performance.

**Comment by Sanderli25** [comment]
@Adrian2k Skjønner det. Var forresten ikke ment detaljnivå på Flesland. Ser ut som veldig lette streker på bygningene + jetways. Man kan jo spare sektorfilen for "punkter" ved å fjerne andre "smådetaljerte" bygninger på andre flyplasser da. Trenger heller ikke legge inn alle bygningene som er gjort på Flesland sitt kart IRL.

**Comment by morettio** [comment]
Hvorfor endre ting bare for å endre det? Jeg ser ikke grunnen til å endre dette siden det funker og er stabilt i ES. er mange andre ting som ligger høyt over i prioriteringslista.
