### ISSUE TITLE
Add ENSV guest owner in ZV_TMA for BR arrivials

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#181]

**Comment by meltinglava** [comment]
Should we do this the other way as well?

**Comment by Adrian2k** [comment]
No. It is quite rare to have UPDER arrivials into ZV compared to ALUVA/BADAB into BR.
It is subject for coordination regardless.

**Comment by Adrian2k** [comment]
ENZV_APP:ENZV:*
ENSV_CTR:*:ENBR
ENSV_N_CTR:*:ENBR
ENSV_E_CTR:*:ENBR
ENOR_S_CTR:*:ENBR
ENOR_CTR:*:ENBR
