### ISSUE TITLE
Enable "Raw Video" for airports with Surface Movement Radar

### ISSUE THREAD

**Issue by thor** [Vatsim-Scandinavia/ENOR-Sectorfile#183]
Applies to:

- ENGM
- ENZV
- ENVA
- ENBR

Is it possible to enable _Raw Video_ in the Ground Radar plugin by default, and thus simulate[^1] the SMR[^2] used by the aerodromes above?

[^1]: To some extent.
[^2]:  [Surface Movement Radar](https://www.skybrary.aero/articles/surface-movement-radar)

**Comment by krislarsen** [comment]
Was trying to see some refernce images and they have indeed a afterglow enabled. So this could be something to be looked at.

**Comment by Adrian2k** [comment]
Will enable it as default, but not with the intense default settings.

**Comment by Adrian2k** [comment]
![image](https://user-images.githubusercontent.com/35482228/229582100-1271d9e8-97cc-44f7-8f37-158aa9ec684f.png)
