### ISSUE TITLE
AIRAC - ENRE VRP Points

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#184]
Not sure how relevant it is for the sectorfile, but there are now VRP's published.

**Comment by Adrian2k** [comment]
@krislarsen @morettio

**Comment by Adrian2k** [comment]
Dette er Rena, ikke Hamar

**Comment by morettio** [comment]
Om AFIS blir laga så kan vi legge det inn. Tenker vi tar det opp da :)
