### ISSUE TITLE
AIRAC - ENBR VAC Chart

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#186]
"Complete revision"

Chart published in AIP is not valid, correct chart published in AIP SUP - https://avinor.no/globalassets/_microsite/ais-portal/aip-sup/en_sup_2023_005_en.pdf

**Comment by Adrian2k** [comment]
@krislarsen tagger deg også da det krever SOP endring antar jeg.

**Comment by morettio** [comment]
![image](https://user-images.githubusercontent.com/59777657/227267992-9489d701-60a8-4045-a595-179760953209.png)
Ikke på charts

**Comment by krislarsen** [comment]
> @krislarsen tagger deg også da det krever SOP endring antar jeg.

Er ikke umiddelbart noe som pårører SOP, men kan informere videre
