### ISSUE TITLE
AIRAC - ENZV RNP Z 18 & 36

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#193]
New name

**Comment by Adrian2k** [comment]
Krever det endring i dokumentasjoner?
SOP elns? @krislarsen

**Comment by krislarsen** [comment]
> Krever det endring i dokumentasjoner? SOP elns? @krislarsen

Er ingen LOP/SOP som dekker dette. Ingen endringer på denne delen
