### ISSUE TITLE
Git to GNG sync 2303

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#204]
Fortsatt noen små ting som skal gjøres først, men følgene filer kommer opp med changes.

![image](https://user-images.githubusercontent.com/35482228/229577081-ce8dc9dd-f807-423c-8992-f0379625eb94.png)

**Comment by Adrian2k** [comment]
No content change found:
DiscordRadioCallsings
TopSkyCallsigns
TopSkyLocalCallsigns
TopSkySSRCodes
TopSkySymbols
General

**Comment by morettio** [comment]
rart, symbols og ssr er ikke endra i denne updaten

**Comment by Adrian2k** [comment]
> rart, symbols og ssr er ikke endra i denne updaten

Som skrevet, no contect change found - så sikkert GNG som har filene i et anna format.

**Comment by morettio** [comment]
Jeg lasta opp Maps på denne datoen. stemmer med GNG

![image](https://user-images.githubusercontent.com/59777657/229581417-b25a37ac-72dd-4ea6-aa55-97e31cf82dbd.png)
