### ISSUE TITLE
S6->S13 CFL/XFL Discrepancy to ENBR

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/ENOR-Sectorfile#208]
When controlling ENOS_CTR, you get a CFL/XFL Discrepancy to ENBR. See AMV154 as example. He was still before sector boundries.

![Screenshot_2023-04-18_20-26-00](https://user-images.githubusercontent.com/2505044/232869740-22dce815-66d1-4179-b884-13657e615610.png)

**Comment by krislarsen** [comment]
Note to myself:
AMV154 is flying via S8 to S9

**Comment by Adrian2k** [comment]
https://statsim.net/flights/flight/?flightid=12254248

**Comment by meltinglava** [comment]
The weird part here is that ES says these aircraft go through S6.

**Comment by krislarsen** [comment]
Possible fix on the issue will be pushed with the upcoming sectorfile update. If the error still happens, let me know @blt950

**Comment by Adrian2k** [comment]
Merged into one issue #290
