### ISSUE TITLE
AIRAC 2305

### ISSUE THREAD

**Issue by morettio** [Vatsim-Scandinavia/ENOR-Sectorfile#209]
- END263 DONE
- ENT121 E6 DONE
- STM replaced (mulig ingen endring, men må sjekke ENBO) No changes for Topsky
- ENZV SID/STAR changed
- ENZV VAC

**Comment by krislarsen** [comment]
> * STM replaced (mulig ingen endring, men må sjekke ENBO)
STM is replaced with ODNOS. All STMxx SID/STARs is nowe ODNOSxx 

> * ENZV SID/STAR changed
> * ENZV VAC
**New procedure for visual approach**
DESCENT CLEARANCE FOR VISUAL APCH
DESCENT BELOW 2000 FT IS SUBJECT TO SPECIFIC
CLEARANCE FROM ATC

Possible CTA adjustments. As far as I can see it's not similar coordinates.
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/ed0883fe-189c-4beb-b6a3-f0e18484a4fc)

Area I adjusted
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/f02635b3-0ba5-4beb-97d8-6920dbcd5532)

**Comment by Adrian2k** [comment]
Following coordinate very slightly moved

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/1906746b-9691-4e20-8bbd-103a6361c7f9)

**Comment by Adrian2k** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/4f27cf58-3e55-4d01-bbf5-4e5143694a34)

Tiny adjustment AREA  I

**Comment by Adrian2k** [comment]
ENDU parking coordinates to be updated

**Comment by Adrian2k** [comment]
ENZV new heli proc

**Comment by morettio** [comment]
END263 DONE
ENT121 E6 DONE

Topsky done @Adrian2k

**Comment by Adrian2k** [comment]
All done
