### ISSUE TITLE
Destination element in tag not hidden in CJI filtering

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#210]
Don't know if this can be an easy fix by either requesting Topsky dev for a two-letter destination label that is hidable in CJI filtering or ask the NATCON dev for enhancement in the feature. This is a request for enhancement so low priority on this one

**Comment by morettio** [comment]
I made a forum post on Vatsca

https://vatsim-scandinavia.org/forums/topic/4595-two-letter-destination-label/

**Comment by marud94** [comment]
`Yes, the plugin setting "Label_ADES_MaxChars=x" (where x is the number of characters to display, from 1 to 4) defines how many last characters of the destination ICAO code are displayed in the label item. The ADES list item will always display the whole ICAO code.`
@morettio

**Comment by morettio** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/59777657/2aa77253-15d9-4977-b562-0267a012ba0a)

**Comment by morettio** [comment]
Done in 6a4f4c9

**Comment by krislarsen** [comment]
Great!

Might take wrong here, but has the NATCON.dll plugin any other function than the destination code? Maybe time to unload it if not?
