### ISSUE TITLE
NATCON CPDLC Route Draw differs between S/A+C mode

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/ENOR-Sectorfile#212]
Now when Euroscope is actually supporting S/A+C mode aircrafts, I found a little TAG "bug".

In S-mode, the route toggle draw is on left button for autohide
![Screenshot_2023-05-08_21-01-21](https://user-images.githubusercontent.com/2505044/236910166-7a9db72e-682c-424b-8c06-95e600142fe4.png)

In A+C mode, the route toggle draw is on right button for autohide 😭 
![Screenshot_2023-05-08_21-01-36](https://user-images.githubusercontent.com/2505044/236910175-97cb92b3-5af8-4d3e-a0be-cf22cce66061.png)

**Comment by Adrian2k** [comment]
S mode is not supposed to be activated in the sectorfile afaik.
Seems odd, since we have not defined any S-mode transponders and coorelation mode is on C-mode.

**Comment by morettio** [comment]
@blt950 
Try downloading tags again, The problem is not in the sectorfile:
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/59777657/19023d7f-3ff2-4c47-a5dc-da2f09fb2809)
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/59777657/bcdcd92e-67a9-4cba-aa3f-beceb089da91)

**Comment by blt950** [comment]
> @blt950 Try downloading tags again, The problem is not in the sectorfile:

I think I solved it by doing that yeah.


> S mode is not supposed to be activated in the sectorfile afaik. Seems odd, since we have not defined any S-mode transponders and coorelation mode is on C-mode.

Where is it set to be activated/deactivated? I see different dots based on aircraft is S or A+C
![Screenshot_2023-05-08_19-48-56](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/2505044/cd960aa1-10ea-4b95-a269-681d3789cc5b)

**Comment by morettio** [comment]
`Where is it set to be activated/deactivated? I see different dots based on aircraft is S or A+C`
Maby @Adrian2k can answer that

**Comment by Adrian2k** [comment]
Not too familiarized with how ES handles mode S, but within general settings we have not defined anything that would make it support mode S..

How does your general settings look like?

**Comment by blt950** [comment]
@Adrian2k My general settings
![Screenshot_2023-05-14_12-26-18](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/2505044/1447fd7c-4b15-43e0-bcc0-d44dbc73c9b2)

**Comment by Adrian2k** [comment]
Why do you have simulation of radar coverage disabled?

**Comment by blt950** [comment]
> Why do you have simulation of radar coverage disabled?

No idea TBH :) Shouldn't be off. I'll turn it on again and see if it helps the issue

**Comment by blt950** [comment]
Enabling radar setting solved the issue. Not sure why it was off, but thanks anyways.
