### ISSUE TITLE
ENHD-EPGD triggered 310 XFL discrepancy ENSV->ENOS

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/ENOR-Sectorfile#214]
![Screenshot_2023-05-15_21-56-11](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/2505044/2e112cd3-baf0-4d03-bed5-11355dbd15f1)

ENHD-EPGD triggered 310 XFL ENSV->ENOS

**Comment by Adrian2k** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/772d4740-1d4a-43d9-a976-d34bb0062888)

As intended.

**Comment by blt950** [comment]
*facepalm*
