### ISSUE TITLE
COPX OKSAT

### ISSUE THREAD

**Issue by janfelhut04** [Vatsim-Scandinavia/ENOR-Sectorfile#218]
Sender COPX til ENOS for OKSAT når CFL er satt til 210. 
![COPX OKSAT](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/126728914/9c997d7d-2d2e-4bf6-9079-54e0a0f8340d)

**Comment by marud94** [comment]
Hvilket fly er det, posisjon og gjerne vis hele strippen og egentlig radarbildet. Det lar seg vanskelig gjøre å feilsøke/gjenskape basert på den lille infoen som er her.

**Comment by janfelhut04** [comment]
![COPX OKSAT](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/126728914/555e33d3-af66-4afc-a0ca-ae424c606e84)
Var ca der, passerte 6000ft

**Comment by krislarsen** [comment]
Hvilken bane tok denne av fra @janfelhut04 ?

**Comment by janfelhut04** [comment]
> Hvilken bane tok denne av fra @janfelhut04 ?

19L.

**Comment by krislarsen** [comment]
> > Hvilken bane tok denne av fra @janfelhut04 ?
> 
> 19L.

Og hva stod i XFL?

**Comment by janfelhut04** [comment]
> > > Hvilken bane tok denne av fra @janfelhut04 ?
> > 
> > 
> > 19L.
> 
> Og hva stod i XFL?

210 mener eg. Fikk heller ikke opp 4R eller noe mens jeg valgte waypointet i listen

**Comment by krislarsen** [comment]
Dette er et vanskelig område å jobbe med COPX-messig der den ofte driver å kalkulerer mellom ulike COPXer. Derfor kan det oppstå fra en tid til annen at den bommer og det kan være flere eksterne faktorer til det. Denne blir ikke prioritert med mindre det kommer flere slike feilmeldinger på den.

**Comment by Adrian2k** [comment]
Closed by request from @janfelhut04
