### ISSUE TITLE
Lower limit label for Oslo TMA wrong in area vestby

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#219]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/f27ccf83-6e17-4e5a-ab0b-63d62098597d)
should be 55

**Comment by krislarsen** [comment]
The sector itself is now defined from 5500 feet. It's only the label that was forgotten with the change. Will be fixed most likely to next update.

**Comment by Adrian2k** [comment]
Updated in GNG, pending update in .asr file.
