### ISSUE TITLE
COPX 8R>9R ENBR XFL320

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#220]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/052da4f7-8f28-4abb-8846-86b4d880bdd2)

It happens again.
Forøverig så indikerte også FIN8DR sin XCOP med teksten "8R > 9R"

**Comment by krislarsen** [comment]
Med eller uten direct?

**Comment by krislarsen** [comment]
Mulig XFL endrer seg ved DCT. Mulig jeg må se på sortorder, kan du bekrefte om det er riktig XFL eller ikke _uten_ DCT?

**Comment by Adrian2k** [comment]
XFL320 på samtlige via sector 8

**Comment by krislarsen** [comment]
Får også XFL på FL310 (ident: 9R>8R) på fly fra ENBR via S8 når jeg sitter ENSV_CTR nå

Og så fikk jeg et fly som var via ULVAN og fikk DCT VALPU (ENBR-ENGM) som fikk 9R>8R ident
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/7c43391e-30d4-4747-b134-3297a16b61ed)

**Comment by blt950** [comment]
Kan bekrefte samme issue på ENOR_S_CTR som Krister over ang. 9R>8R og XFL 310.
![Screenshot_2023-06-05_20-45-11](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/2505044/864edfb4-65ae-43c8-8a79-5e479cd363c1)

**Comment by krislarsen** [comment]
Still an issue. Might move all things from COPX Fix to Fix after to see if issue will be solved by that

**Comment by Adrian2k** [comment]
Merged into one issue #290
