### ISSUE TITLE
Incorrect use of magnetic wind ATIS

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#224]
ENTC, ENBO, ENEV, ENDU all seem to have 10 degrees subtracted in the ATIS.
This is incorrect, should only apply for airports east of ENTC (excluding ENTC).

**Comment by marud94** [comment]
Reported to VATATIS admin, our airports are correctly configured.

**Comment by marud94** [comment]
VATATIS dev reports this as being fixed. Must be verified before closing issue. Will see when I hate time later.

**Comment by marud94** [comment]
Tested and verified working as expected
