### ISSUE TITLE
ATIS for clearance contact with ENKR_TWR

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#225]
FOR CLEARANCE AND START UP, CONTACT KIRKENES TOWER 118.1 

Shouldn't this just say "Tower"?

**Comment by marud94** [comment]
It's weird that it does that, as the setup there is identical to ENBR for example, which does not do it like that..

**Comment by marud94** [comment]
Found issue, name was set to "HOYBUKTMOEN" which made position different than what VATATIS expected and then printed full position name. Now works as expected.
