### ISSUE TITLE
ENMH default type is ILS

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#226]
There is no ILS on ENMH

This is Mehamn Information Victor .. time 1650 .. expect ILS approach .. Runway in use 17 .. runway condition wet .. Transition level 85 .. For clearance and start up, contact Polaris Control 126.7 .. wind 240 degrees 18 knots .. visibility 10 kilometers or more .. light rain .. Clouds FEW 1000 FT BKN 3000 FT .. TMP 5 DP 1 .. QNH 1001.

**Comment by Adrian2k** [comment]
Perhaps it should not even suggest an approach type since its not within an TMA?
Investigate how it is IRL.

**Comment by marud94** [comment]
ENMH didn't have configurable runways in the setup, deleted and remade. Configured both runways to say RNP as default for now.
