### ISSUE TITLE
No red line between TWR and GND on ENVA

### ISSUE THREAD

**Issue by vegsor** [Vatsim-Scandinavia/ENOR-Sectorfile#230]
When TWR logged on at Værnes, no red line appeard for both TWR and GND.  Sector file version: 20230519203746-230501-0002
![Skjermbilde 2023-05-27 125132](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/134779268/7db89a41-aa0a-4539-8c31-acdebe541ae9)

**Comment by Adrian2k** [comment]
Fixed
