### ISSUE TITLE
AIRAC - CTA Areas & ENBR TMA adjusted

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#235]

**Comment by Adrian2k** [comment]
ENBR TMA finished 
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=c5d37bbc-0dcc-11ee-b5bd-6595d9b17862

**Comment by Adrian2k** [comment]
S17, S18 and S19 lower limits updated in GNG - neighboring sectors adjusted.

Remaining:

- [ ] Test in sweatbox to see active sectorlines work
- [ ] Double check Møre TMA and Sogn TIA borders
- [ ] Update lower limits display
- [ ] Check for lower limits defintions in add display and copx

**Comment by Adrian2k** [comment]
`Additional Display Sector: ENOR·ENAL-MØRESTA·025·175 - Line: ENOR·S18-LOWER9·175·195|BOTH|A:ENOR432-ENOR433-ENOR434 - Other Sector not found

Additional Display Sector: ENOR·ENKB-MØRENTA·007·175 - Line: ENOR·S18-LOWER9·175·195|BOTH|A:ENOR432-ENOR78 - Other Sector not found

Additional Display Sector: ENOR·ENOLTA·025·175 - Line: ENOR·S18-LOWER9·175·195|BOTH|A:ENOR431-ENOR886 - Other Sector not found

Additional Display Sector: ENOR·ENOLTA·035·055 - Line: ENOR·S18-LOWER9·175·195|BOTH|A:ENOR2911-ENOR2912 - Other Sector not found

Additional Display Sector: ENOR·ENOLTA-2·035·175 - Line: ENOR·S18-LOWER9·175·195|BOTH|A:ENOR431-ENOR81 - Other Sector not found

vACC COPX "TOGAT" ignored, To Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "TOGAT" ignored, From Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "AMOXA" ignored, To Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "AMOXA" ignored, From Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "EKTAK" ignored, To Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "EKTAK" ignored, From Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "GIGNI" ignored, To Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "GIGNI" ignored, From Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "TOMBO" ignored, To Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "TOMBO" ignored, From Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "1R>19R" ignored, To Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "19R>1R" ignored, From Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "7R>19R" ignored, To Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?

vACC COPX "19R>7R" ignored, From Sector 'ENOR·S19-LOWER2·075·175' not found. Did you mean 'ENOR·S17-LOWER2·075·175' ?`

**Comment by krislarsen** [comment]
COPX related errors has now been adjusted.

**Comment by Adrian2k** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/cc299f1e-12a9-4ca3-ad92-cb385445a8d0)
