### ISSUE TITLE
ENDU SID 28 SJA 

### ISSUE THREAD

**Issue by Skofte** [Vatsim-Scandinavia/ENOR-Sectorfile#240]

**Comment by Skofte** [comment]
Random SJA dep in SID list with no designation behind.
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/135712204/663a5b99-0972-4b2d-9b23-0d742bde949d)

**Comment by Adrian2k** [comment]
It is a military departure, without any designator
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/646ea470-049a-4c90-8a9e-055653f740db)

Will see if we can change the designator to specify its a MIL SID.

**Comment by Adrian2k** [comment]
No easy way to change the name..

Changed the sort other to be:

-RNAV SID
-Conventional SID/OMNI
-MIL SID
-VFR/Other
