### ISSUE TITLE
ENZV default app 28

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#243]
This is Sola Information Golf .. time 1820 .. expect ILS 28 approach .. Runway in use 28 .. Transition level 85 .. runway condition damp .. For clearance and start up, contact Ground 121.75 .. wind 290 degrees 16 knots .. Visibility 4000 meters .. Clouds FEW CB 200 FT BKN 400 FT BKN 900 FT .. TMP 15 DP 15 .. QNH 1006 .. Recent rain.

Should be RNP

**Comment by Adrian2k** [comment]
Ehm, runway 10/28 does not excist anymore in vATIS

**Comment by marud94** [comment]
Seen that happen in some airports before as well. Only fix is to delete the
airport and add it again...

lør. 1. jul. 2023, 18:25 skrev Adrian Bjerke ***@***.***>:

**Comment by marud94** [comment]
Fixed and published
