### ISSUE TITLE
Quick setup guide CDM

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#244]
Possible to create a quick CDM guide, which can be used when CDM suddenly needs to be used on short notice?
Very few controllers have experience with CDM.

Could also be put into the current guide, for example a quick overview what does what, how to get a CTOT and how to activate master - then detailed info on the pages below.

Perhaps also just use the wiki? Move away from publishing documentation via sectorfile, keep everything at the same place (in this case we also need to replace the PDF provided with a link to wiki so it overwrites old pdf files).

**Comment by marud94** [comment]
Manual updated on wiki WIP page, awaiting feedback.
Will later publish and replace PDF with wiki-link
