### ISSUE TITLE
ATIS once again says datalink available incorrectly

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#245]
OSLO GARDERMOEN INFORMATION PAPA .. TIME 1650 .. EXPECT ILS OR
RNP APPROACH .. RUNWAYS 19L AND 19R IN USE .. TRANSITION LEVEL
85 .. **FOR EN-ROUTE CLEARANCE REQUEST VIA DATALINK OR CONTACT
TOWER 118.3 ..** MET REPORT .. WIND 210 DEGREES 12 KNOTS .. CAVOK
.. TMP 25 DP 10 .. QNH 1010 .. ACKNOWLEDGE INFORMATION PAPA ON
FIRST CONTACT.

ENGM_TWR online without PDC connected
ENOS_CTR online with PDC connected

This have happend before aswell with this combination (TWR without, CTR with)

**Comment by Adrian2k** [comment]
Issue forwarded to vatatis admin

**Comment by Adrian2k** [comment]
Happening again @marud94 

ENSV has DLC online, ENHD_TWR does not.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/de44c395-e8f9-4c06-a312-ae01d715c67d)

**Comment by marud94** [comment]
Forwarded to dev

lør. 26. aug. 2023, 19:55 skrev Adrian Bjerke ***@***.***>:

**Comment by Adrian2k** [comment]
Should be fixed now
