### ISSUE TITLE
EKDK Sector L frequency display

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#248]
See new LOA proposoal
Need topsky to display new frequency

**Comment by Adrian2k** [comment]
EKDK_L_CTR been given CJI EKL

**Comment by morettio** [comment]
Rekker ikke å se på dette før søndag, om ikke så blir det i slutten av neste uke.

**Comment by Adrian2k** [comment]
Resolved in [76814d0](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/commit/76814d0ca0a377cbee9c2b7aa9dbf77cd0bd414a)
