### ISSUE TITLE
Atis says contact tower when ground is the only one online

### ISSUE THREAD

**Issue by vegsor** [Vatsim-Scandinavia/ENOR-Sectorfile#249]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/134779268/6bb749e1-f218-4d71-9f09-062efb243e62)
Logged on as ground at flesland and the atis says contact tower on the tower frequency instead of ground on ground frequency

**Comment by marud94** [comment]
@vegsor It shows correct now, was Tower online earlier while you were online or just before you logged on?

**Comment by vegsor** [comment]
dont think so, when i logged on nothing was online at least
