### ISSUE TITLE
DCT LOKSA shows waypoint in Finland

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#251]
Issue related to #87 , but in a new form/type

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/aa7d08c8-1036-44f2-888a-b27dc03e2aae)
Even if you use the point function in topsky and select the waypoint in Denmark, it will show the same tracking and select the waypoint in Finland.

**Comment by Adrian2k** [comment]
Issue identified
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/a0c0dcc4-4180-406e-8709-b9424a629ca8)

**Comment by mjpikat** [comment]
Added to @estvacc task list, will deal with that in the morning!

**Comment by mjpikat** [comment]
Fixed
