### ISSUE TITLE
Duplicate Postions profiles in TopSky to Mentor/Examniee positions

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#255]
Nice for mentors to see the same view as the student is getting when connecting to training and examination sessions. If this will create a backlog in maintainance when there is changes in the profile, I suggest not fixing this unless there is a function to "slave" the main profile/position

Not must for every position, but ENBR, ENVA, ENGM, ENOS (main) and ENSV (main) would be nice.

**Comment by Adrian2k** [comment]
You should get the same displays activated when you prime the frequency?

**Comment by morettio** [comment]
Topsky does not have that functionality. You need to prime the frequency.
