### ISSUE TITLE
EK + EKL labels on top of each other

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#258]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/4cae9142-25f5-4faf-948e-6e55746e308f)

**Comment by Adrian2k** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/aef4efbe-1e36-4a97-90d0-653d45882869)
