### ISSUE TITLE
Weird letter in Tromsø tower

### ISSUE THREAD

**Issue by marud94** [Vatsim-Scandinavia/ENOR-Sectorfile#263]
See info line 1

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79376555/82d10792-d029-43da-9dc4-bcc1e9b335ae)

**Comment by Adrian2k** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/1f7431a6-0816-4bfc-9759-a9e5d8392c2b)

Fine for me?

**Comment by marud94** [comment]
Snålt, var rett for studenten også.. Da er det sikkert noe rart på min side lol
