### ISSUE TITLE
Exclude ENOR_S from ENBD-S (S18 + S19)

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#268]
Keep coming into situations where I would like to sit as ENOR_S, but without being responsible for ENBD_S.
I know for a fact that some other controllers share this thought.

Any opinions from others?
@krislarsen @blt950 @morettio 

In my case the reasons vary a bit, but usually one for these:
1. ENBR and ENGM is online, logging on as only ENOS/ENSV will exclude the other.
2. ENVA and/or Møre usually is "outside" of my main focus and it's easy to forget those.
3. Møre is annoying if you get multiple traffic there, especially for AFIS (ENML+ENOV) which no one understands.

There are 3 possible "solutions" to this.
1. Remove ENBD-S from ENOR_S
2. Convert ENOR_S to ENOR_C and add ENOS_S as a new sector with only ENOS+ENSV.
3. New ENOR position that covers ENSV+ENOS only and ENOR_S remains the same (less pilot confusion)

**Comment by blt950** [comment]
That's the main reason I often don't want to sit ENOR_S. ENBR+ENGM is sometimes more than enough

**Comment by Adrian2k** [comment]
Discussion thread has been made in #norway-controllers chat in discord.

**Comment by Adrian2k** [comment]
ENOR_S will be reduced to ENSV+ENOS only

Need new LOA with Sweden

**Comment by Adrian2k** [comment]
- [ ] LOA Change Sweden
- [ ] Change ENOR_S sectors in GNG
- [ ] Change ENRC_S sectors in GNG
- [ ] ENVA, ENRO, ENOL, ENKB, ENAL, ENML ATIS'es needs new ownership hierarchy
- [ ] VATSpy dataset to be updated
- [ ] Vatglasses dataset
