### ISSUE TITLE
LAPVI1L arrival missing point in ES

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#270]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/4e6cb05a-7efc-462b-b79b-36ea66ae304e)

**Comment by Adrian2k** [comment]
Have you selected a STAR?

STAR:ENNA:16:LAPVI1L·LOC·Z:LAPVI NEPKO BK112 BK92 BK30
STAR:ENNA:16:LAPVI1L·LOC·Y:LAPVI NEPKO BK112 BK92 BK30

**Comment by meltinglava** [comment]
Yes. I had it with LOC Z app. But might be a ES bug. Guess we need to repoduce

**Comment by Adrian2k** [comment]
Next time it could been useful with more details, such as the flightplan window (F1 + A)

I suspect this case has something to do with the flightplan, as the STAR is included in the sectorfile.
