### ISSUE TITLE
Implementation of 8.33khz spacing

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#273]
Planned 2nd Nov

Frequencies:
ENGM_W_DEL
ENGM_E_DEL
ENGM_W_GND
ENGM_E_GND
ENGM_Q_GND

Other frequencies using 8,33 in Norway which is not included in the sectorfile:

ENBD Sector 27 - 134.515

**Comment by Adrian2k** [comment]
- [ ] Awaiting approvoal from EUD
- [ ] Check if any LOP needs updating
- [ ] Adjust frequencies in GNG
- [ ] Adjust frequencies in AFV
- [ ] Adjust frequencies in VATATIS

**Comment by krislarsen** [comment]
**New 8.33 Frequencies | Sweden FIR**

- ESMM_4_CTR 124.405
- ESMM_5_CTR 132.765 
- ESMM_2_CTR 127.755 

- ESOS_CTR 118.405
- ESOS_N_CTR 132.155
- ESOS_3_CTR 131.130

- ESKS_TWR 124.460

**Comment by krislarsen** [comment]
> Awaiting approval from EUD

New frequencies requested

**Comment by krislarsen** [comment]
**New 8.33 Frequencies | Copenhagen FIR**

- EKDK_N_CTR 134.680
- EKDK_L_CTR 123.555
- EKDK_V_CTR 135.565
- EKDK_D_CTR 133.155
- EKDK_B_CTR 119.555
- EKDK_CTR 136.485

**Comment by Adrian2k** [comment]
EKDK N:
EKDK_N_CTR 134.680
EKDK_S_CTR 136.555
EKDK_V_CTR 135.565
EKDK_L_CTR 124.555
EKDK_CTR 136.485

Sector V:
EKDK_V_CTR 135.565
EKDK_L_CTR 124.555
EKDK_S_CTR 136.555
EKDK_N_CTR 134.680
EKDK_CTR 136.485

Sector L (GND-FL285)
EKDK_L_CTR 124.555
EKDK_V_CTR 135.565
EKDK_S_CTR 136.555
EKDK_N_CTR 134.680
EKDK_CTR 136.485

**Comment by Adrian2k** [comment]
ESMM4:
ESMM_4_CTR 124.405
ESMM_5_CTR 132.765
ESMM_2_CTR 127.755
ESOS_1_CTR  118.405

ESOS3:
ESOS_3_CTR 131.130
ESOS_1_CTR 118.405

ESOSN:
ESOS_N_CTR 132.155
ESOS_3_CTR 131.130
ESOS_1_CTR 118.405

ESOSK:
ESOS_K_CTR 131.055
ESOS_N_CTR 132.155
ESOS_3_CTR 131.130
ESOS_1_CTR 118.405

**Comment by krislarsen** [comment]
**LOA Updates**

- [ ] EKDK
- [ ] ESAA
- [ ] EGPX

**LOP Updates**

- [ ] ENGM

**Comment by Adrian2k** [comment]
Changed following frequencies in GNG:

W_GND 121.605
E_GND 121.905
W_DEL 121.680
E_DEL 121.930
Q_GND 121.730

**Comment by meltinglava** [comment]
> **LOP Updates**
> 
>     * [x]  ENGM

Frequencies not listed in LOP. So no update is needed.

**Comment by krislarsen** [comment]
https://fsmine.dhis.org/vateud8/
@Adrian2k Check frequencies are according to the publised frequencies
