### ISSUE TITLE
VATATIS Changes

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#280]
Related to issue #278 & issue #268 & issue #274

Collected all ATIS changes to one issue

ENRC_CTR > ENRC_N_CTR
ENSV_10_CTR > ENSV_W_CTR
ENSV_15_CTR > ENSV_16_CTR

--- 

ENOR_S_CTR and ENRC_S_CTR will no longer cover ENBD-S
**Affected airports:** ENRO, ENVA, ENOL, ENKB, ENAL, ENML

---

ENRC_N_CTR (previously ENRC_CTR) will no longer cover ENOS+ENSV
**Affected airports:** ENGM, ENTO, ENRY, ENCN, ENZV, ENHD, ENBR, ENSG, ENFL, ENBL

Hopefully, the remaining airports in ENBD will automatically change to ENRC_N_CTR, but should be double-checked.

---

ENSV_W and ENSV_16 do not cover any airports, but they do cover offshore - so it is likely that Tampen and Ekofisk ATIS need a touch.

**Comment by krislarsen** [comment]
>ENSV_W and ENSV_16 do not cover any airports, but they do cover offshore - so it is likely that Tampen and Ekofisk ATIS need a touch.

Positions are added in VATATIS, though I can't see there is an existing Position Priority on ENLE or ENHC (Offshore). This is not urgent though. I'll close this and if you want to make a position priority for these positions, please open a new issue and refer to this.
