### ISSUE TITLE
Add ENTO Ground radar support

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#284]
Add a ground asr file to ENTO due to ENTO LVP procedures in LOP and AIP AD 2.22 - 1.4: GND SUR is used during LVP.

I have made a suggestion to what could be in the GRpluginStands.txt file, based on Torp LOP parking:

```
//// ---- ENTO ---- /////

//STAND 1
STAND:ENTO:1:N059.10.47.690:E010.15.14.020:20
CODE:C:D
PRIORITY:-1

//STAND 2
STAND:ENTO:2:N059.10.46.590:E010.15.14.350:18
ADEP:EN
CODE:C

//STAND 3
STAND:ENTO:3:N059.10.45.280:E010.15.14.370:18
ADEP:EN
CODE:C

//STAND 4
STAND:ENTO:4:N059.10.43.970:E010.15.14.390:18
ADEP:EN
CODE:C

//STAND 5
STAND:ENTO:5:N059.10.42.660:E010.15.14.390:18
ADEP:EN
CODE:C

//STAND 10
STAND:ENTO:10:N059.10.47.950:E010.15.11.770:18
CODE:C
SCHENGEN

//STAND 11
STAND:ENTO:11:N059.10.47.950:E010.15.09.220:18
CODE:C
SCHENGEN

//STAND 12
STAND:ENTO:12:N059.10.47.940:E010.15.06.670:18
CODE:C
SCHENGEN

//STAND 13
STAND:ENTO:13:N059.10.47.930:E010.15.04.130:18
CODE:C
NON-SCHENGEN

//STAND 14
STAND:ENTO:14:N059.10.48.030:E010.15.01.590:18
CODE:C
NON-SCHENGEN

//STAND 15
STAND:ENTO:15:N059.10.48.020:E010.14.59.040:18
CODE:C
NON-SCHENGEN
PRIORITY:-3

//STAND 32
STAND:ENTO:32:N059.11.08.540:E010.15.22.460:12
CODE:B

//STAND 33
STAND:ENTO:33:N059.11.09.410:E010.15.22.460:12
CODE:B

//STAND 34
STAND:ENTO:34:N059.11.10.280:E010.15.22.460:12
CODE:B
```

**Comment by krislarsen** [comment]
This is a change that looks okay from my perspective.

**Comment by Adrian2k** [comment]
//STAND 15
STAND:ENTO:15:N059.10.48.020:E010.14.59.040:18
CODE:C
NON-SCHENGEN
PRIORITY:-3

Why is this prio -3?

**Comment by Sanderli25** [comment]
> Why is this prio -3?

According to Jonas Johannes, earlier Ground Handler at Torp, Stand 15 has lower priority, due to being a quite narrow parking and tight pushback.

**Comment by Adrian2k** [comment]
With the current setup, stand 15 will only be used for non-schengen flights when stand 13, 14 and 1 is occupied.
Is this the intention, or does stand 1 has lower priority than stand 15 for non-schengen?

If you want start 13-15 to be filled before stand 1, we will have to adjust the priorites.

**Comment by meltinglava** [comment]
I guess you want to save stand 1 for CODE:D

**Comment by Sanderli25** [comment]
> If you want start 13-15 to be filled before stand 1, we will have to adjust the priorites.

My bad, this is indeed correct. IRL, pass Control is by the non  Schengen area; stands 13 - 14 - 15, which is Why these would be filled first.
