### ISSUE TITLE
topsky map freq not updated to 8.33

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#285]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/0a61d5ee-a8fd-4660-ba7f-c1559f15a3e0)

**Comment by Adrian2k** [comment]
https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/blob/ca3ad979c5fa4cb090131323da9871c39113e054/Plugins/TopSkyMaps.txt#L4559C49-L4559C49

It is updated

**Comment by meltinglava** [comment]
rgr. Think that file got left out. Goig to update that again

**Comment by meltinglava** [comment]
rgr. Think that file got left out. Goig to update that again
