### ISSUE TITLE
Fix INSOD duplicate

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#286]
The IAF INSOD shows wrong name (INSOT) when hovered over with keybind "Alt."  Both INSOD and INSOT is added in both the list of fixes in display settings and in the TopSkyMaps MISC category.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/a4eed4a4-f296-4116-ad46-f1e40cb25485)

**Comment by Adrian2k** [comment]
Can't fix - the issue does not "belong" to us.

It is an AIRAC data issue, the data comes from Aerosoft which again comes from LIDO.

**Comment by Adrian2k** [comment]
TopSkyMaps MISC category - this is autogenerated maps from the included AIRAC data in the sectorfile
