### ISSUE TITLE
BR APP not allowed to send VALDI without COPX 

### ISSUE THREAD

**Issue by marud94** [Vatsim-Scandinavia/ENOR-Sectorfile#287]
SOP says BR APP can route flights to GUNPA and VALDI if in their flightplans without prior coordination. When selecting VALDI in the direct list it says it will send COPX to ACC.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79376555/8224c72a-0c67-41cd-8f75-f19c126b6677)

**Comment by krislarsen** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/0130c0f7-3902-4c73-85f6-20fc549f1cba)
Both VALDI and GUNPA were added in GNG. Have adjusted Sortorder and moved the respective point from COPX FIX to Fixafter. Testing is nessesary.

**Comment by marud94** [comment]
Tried testing on sweatbox, ended up with it sending COPX for REKLI as well. Need more testing, preferably on live network.

**Comment by Adrian2k** [comment]
To be continued in #496
