### ISSUE TITLE
Aman ENZV

### ISSUE THREAD

**Issue by TryFanGamer** [Vatsim-Scandinavia/ENOR-Sectorfile#288]
i have made AMAN fro Sola if this can be added :-)

		"ENZV":{
			"targetFixes": [ "ENZV" ],
            "viaFixes": [ "BEGOD", "KUNEM", "UNBUD", "RIVEX", "IDIPI", "ROPNO", "UPDER"  ],
            "tagLayout": "SinglerunwayLayout",
            "destinationAirports": [ "ENZV" ]
		}

**Comment by TryFanGamer** [comment]
Added ENHD to for fune
		"ENHD":{
			"targetFixes": [ "ENHD" ],
            "viaFixes": [ "BEGOD", "KUNEM", "UNBUD", "RIVEX", "IDIPI", "ROPNO", "UPDER" ],
            "tagLayout": "SinglerunwayLayout",
            "destinationAirports": [ "ENHD" ]
		}

**Comment by krislarsen** [comment]
Added for review. ENHD is not relevant to add based on traffic level.
