### ISSUE TITLE
Incorrect COPX between ENSV/ENOS/ENBD Boarder

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#290]
This is a combined issue of #208 , #220 & #231 
All of theese issue is due to incorrect COPXes. I believe many of the added "dummy" COPX lines made more trouble than solutions. I've removed all unnessesary COPX now and need now a lot of help to check following things:

- [ ] ENBR Dep via S5 and S8 gets RFL
- [ ] ENBR Arr via S8 is handed over to S9 with no descend
- [ ] ENBR arrr via S5 & S6 is getting XFL FL320
- [ ] ENSV can give COPX TNO, AAL and LOKSA without bypassing COPX

Phase 2:

- [ ] TIPAN + BAVTA COPX

Any missing COPX according to SOP/LoA between ENBD/ENSV/ENOS AoR shall be reported here.

**Comment by krislarsen** [comment]
Dev-sectorfiles has been pushed with nessesary changes for testing

**Comment by meltinglava** [comment]
BAVTA + TIPAN

**Comment by krislarsen** [comment]
> BAVTA + TIPAN

Will come as "phase 2" testing

**Comment by Adrian2k** [comment]
ENSV_CTR via S9 to ENOR_S_CTR via S8 dep ENBR seems to still trigger XFL F310

**Comment by Adrian2k** [comment]
To be continued in #496
