### ISSUE TITLE
Not showing ATC border (ENGM_W_APP when ENOR_S is online)

### ISSUE THREAD

**Issue by janfelhut04** [Vatsim-Scandinavia/ENOR-Sectorfile#293]
When sitting ENTO_APP and ENOR_S and ENGM_W_APP is online the border towards ENGM isnt showing read
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/126728914/f4477a50-c58d-4e28-a3fe-27c833f5c922)

**Comment by Adrian2k** [comment]
You need to select runway in use at ENGM - their airspace is runway dependent.
