### ISSUE TITLE
CDM - Fly and see santa

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#301]
With fly and see santa upcomming, is there anything CDM specific we need to prepare? Event slots are arrival based afaik.

Do ENTC have CDM support?

@krislarsen @marud94

**Comment by marud94** [comment]
TC is CDM enabled. I need a departure rate and arrival rate that is preferable for the event to ensure the best experience.

**Comment by krislarsen** [comment]
It's a bit hard to determinate a solid arrival and departure rate as it depends if departing traffic requires backtrack or not. Based on my experiences, my suggestion is as followed

**Runway 18:**
Arrival rate: 18 p/h
Departure rate: 12 p/h

**Runway 36**
Arrival rate: 18 p/h
Departure rate: 12 p/h

**Comment by Adrian2k** [comment]
Any way we can prioritize those with booked slot vs those not? All slots are based on arrival time though..

**Comment by marud94** [comment]
> It's a bit hard to determinate a solid arrival and departure rate as it depends if departing traffic requires backtrack or not. Based on my experiences, my suggestion is as followed
> 
> **Runway 18:** Arrival rate: 18 p/h Departure rate: 12 p/h
> 
> **Runway 36** Arrival rate: 18 p/h Departure rate: 12 p/h

Our rates can be amended up to 5 minutes before the event so if you want different rates based on config, that is possible. 

> Any way we can prioritize those with booked slot vs those not? All slots are based on arrival time though..

As long as they are arrival slots we cannot. The CDM system only prioritises bookings based on assigned CTOT

**Comment by marud94** [comment]
- [ ] Updated CAD for arrival rate ENTC
- [ ] Updated rate.txt for departure rate ENTC
