### ISSUE TITLE
COPX IPMOD

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#303]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/613849cc-0e10-403d-a754-8b6e5787f504)

Looks like Polaris gets the DCT IPMOD COPX that are supposed to go to ENGM_W_APP

**Comment by Adrian2k** [comment]
To be continued in #496
