### ISSUE TITLE
Change correlation mode to S-mode?

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#305]
Supposedly both NATCON south and north has mode-s capability now - would it be an idea to change our correlation mode from C-mode to S-mode?

VATSIM has practically no S-mode support other than broadcast of callsign, but this should still be an slight advantage:

1. Traffic inbound from offline sectors will be correlated - IRL you would always get inbound traffic who is correlated.
2. Traffic prediction in ES will be more precise when using AMAN or similar

Mode-S would not remove the requirement for squawk assignment.

**Comment by Adrian2k** [comment]
Quote from ES Wiki:

> S-mode transponders: Unfortunately, there is no support for S-mode in VATSIM and most importantly in the pilot clients, so we must use some other information to simulate a mode-S transponder. EuroScope does this trick by using the equipment code in the flight plan’s remark section. Check the SB3/SB4 documentation about the codes. The default value of this field is IEFGRWQ, which means any aircraft using any of these letters in its equipment code will be regarded as mode-S equipped. That includes nearly all RNAV capable aircraft. To disable all mode-S features, simply clear this field.

**Comment by morettio** [comment]
- [ ] Check Tag's Mode S mode (topsky etc) ref @blt950

**Comment by Adrian2k** [comment]
@krislarsen 

Will need someone to take a decition on this.
IRL they do not get the callsign on the radar via mode S apparantly, as I understand it.

I have been testing it a bit, and personally I find it quite useful to have. It works on about 60-75% of the traffic, depending on what eqipment codes they have. The only difficulty can be is it being harder to spot people without assigned squawk, but when you assume airbone flights without a squawk assigned topsky will automatically assign one to them which then is indicated with yellow above their tag.

**Comment by krislarsen** [comment]
> @krislarsen
> 
> Will need someone to take a decition on this. IRL they do not get the callsign on the radar via mode S apparantly, as I understand it.
> 
> I have been testing it a bit, and personally I find it quite useful to have. It works on about 60-75% of the traffic, depending on what eqipment codes they have. The only difficulty can be is it being harder to spot people without assigned squawk, but when you assume airbone flights without a squawk assigned topsky will automatically assign one to them which then is indicated with yellow above their tag.
> 
> Could also perhaps ask for opinions in the mentor forum.

After some checks, I can confirm this is okay to implement. As you say in original post, aircraft in ENOR FIR still require a unique assigned Squawk.

**Comment by Adrian2k** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/791c8ad9-93cb-48d6-937d-a5812984e542)
@morettio why are non corelated targets showing 5 digits on the squawk code area?

**Comment by Adrian2k** [comment]
Seems its missing a space bewteen ALT and gnd speed

**Comment by morettio** [comment]
I'll Fix it.

**Comment by morettio** [comment]
Done, uploaded to gng

**Comment by Adrian2k** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/7ea3c450-69be-4e26-83ba-0b3da1bd0293)
 
@morettio Can you verify what the * next to the callsign indicates?
It seems to be showing when you have traffic inbound to your sector without an assigned squawk, but can't verify this theory.

**Comment by krislarsen** [comment]
> ![image](https://private-user-images.githubusercontent.com/35482228/296619610-7ea3c450-69be-4e26-83ba-0b3da1bd0293.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNzA5MTEsIm5iZiI6MTcwNTI3MDYxMSwicGF0aCI6Ii8zNTQ4MjIyOC8yOTY2MTk2MTAtN2VhM2M0NTAtNjliZS00ZTI2LTgzYmEtMGIzZGExYmQwMjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDIyMTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MjM1MzdiOWZhMGQ5ZThmNDQ5MWM2YTFkOTZjNGU4MTk1NjEyOWVhMmIzOWM5YjNiMjU4MDgzZmIwNzY1OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJTiGxoYVQECWpYqdz7nqM2zsCtyqyP_PA1gtU_XWio)
> 
> @morettio Can you verify what the * next to the callsign indicates? It seems to be showing when you have traffic inbound to your sector without an assigned squawk, but can't verify this theory.

Not a verification from me, more a confirmation. In the Swedish sectorfile this also shows up when the aircraft does not have an assigned ASSR.

**Comment by morettio** [comment]
What @krislarsen said.
