### ISSUE TITLE
Fly and see santa

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#306]
- [x] Add ENTC_DEL (+ logon profile) - 121.675
- [ ] Define area for ENTC_DEL
- [x] Add holding displays
- [ ] Add route displays
- [x] Enable and check FSS aliases (@marud94)
- [x] Add/enable VATCAN plugin

Anything else?

**Comment by marud94** [comment]
Same routes as last year @krislarsen ?

**Comment by krislarsen** [comment]
> Same routes and holdings as last year @krislarsen ?

Confirmed, no changes in the FSS procedures in Norway
