### ISSUE TITLE
Autoload MVA Helgeland

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#307]
When connecting as ENBN_APP - Helgeland TMA, the MVA does not load MVA automatically as it is not specified in the TopSkySettings.txt file.

Fix:

[ENBN_]
Setup_ScreenLat=ENBN
Setup_LoadMap=MVA\MVA HELGELAND

**Comment by morettio** [comment]
Added to Main
