### ISSUE TITLE
Add ATIS-frequencies to database

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#309]
With reference to [an issue i created in the VectorAudio repository](https://github.com/pierr3/VectorAudio/issues/84), i hereby ask to get the ATIS frequencies below added to the database, as this is required in order to tune them using the mentioned client.

```
    ENBR_ATIS: 125.250
    ENVA_ATIS: 127.550
    ENZV_ATIS: 126.000
    ENTC_ATIS: 126.125
    ENBO_ATIS: 123.900
    ENCN_ATIS: 124.475
    ENTO_ATIS: 119.075
    ENRY_ATIS: 136.175
```

**Comment by Adrian2k** [comment]
Will forward the request to the facility manager for Norway

**Comment by Adrian2k** [comment]
Has been added to AFV now
