### ISSUE TITLE
New EuroScope version v3.2.9

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#315]
https://forum.vatsim.net/t/euroscope-v3-2-4/4106

Will not be recommending our controllers to install this - it seems too unstable at the moment.

**Comment by Adrian2k** [comment]
3.2.7 released - people still reporting about issues on the forum.

Especially the performance seems to be an issue.

**Comment by marud94** [comment]
https://forum.vatsim.net/t/euroscope-v3-2-9/4858

3.2.9 released - no feedback yet.
Mainly bug fixes to previous release.

**Comment by Adrian2k** [comment]
Will close for now, new issue can be opened when a new release has come.
