### ISSUE TITLE
ENDU Misaligned taxiway text 

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#324]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/0a93bc95-acc9-43bd-ad87-25c224a0daf0)
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/0c48f152-875c-4d4f-8811-edb8e834de54)

Misaligned text to highlight C. Hopefully move "C"-text in GA to one place along the red line in the screenshot

**Comment by Adrian2k** [comment]
Fixed
