### ISSUE TITLE
Option to add optional custom ATIS information

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#325]
With the current implementation we are quite restricted in what information can be included in the ATIS.
At winter times, adding information from SNOWTAM like runway conditions for example would be of interest.

**Comment by marud94** [comment]
More examples of what "custom information" you miss would be very helpful. If it's just RWY CCs then we may consider that.

Our goal is to automate it, but we are lacking a way to automatically get snowtams.

**Comment by Atriusftw** [comment]
The more specific runway condition codes is mainly what i'm interested in, but being able to add custom NOTAM could be useful for other scenarios like expected holding delays at high traffic times and hopefully soon, information about de-ice :)

**Comment by Adrian2k** [comment]
Request has been forwareded to the developer.

**Comment by Adrian2k** [comment]
Runway condition codes (1-6) function is already implemented for the UK ATIS variant, so shouldnt be an issue to get implemented in Norway.

Info such as what the runway is covered with (ex. 5mm wet snow) is being looked into in how it could be implemented.

Regarding any custom info - The VatATIS developer is currently reworking the backend system, where the new system would allow us to implement new functions much easier such as for example an &arrhold. 

Regarding having an option of the controllers to add anything they want, I am a bit against of doing. It would be better for the controllers to request new functions for the ATIS.

**Comment by Sanderli25** [comment]
In addition to RWYCC, I would also like the message: "Caution slippery taxiways and runway exits" to be added as an option.

I do not know how different simulators simulate this though.

**Comment by Adrian2k** [comment]
With the new update for vatatis it should be possible for us to make new custom parameters - havent looked into how it acutally is working.

@marud94 will you do some experimenting?

**Comment by marud94** [comment]
@Adrian2k will do!

**Comment by Atriusftw** [comment]
`DANGER AREA, D, 3 5 4 LEKSDALEN` is currently active within ENVA CTR. I see that they have this in the IRL ATIS. Would be nice being able to include this on Vatsim as well.

**Comment by marud94** [comment]
> `DANGER AREA, D, 3 5 4 LEKSDALEN` is currently active within ENVA CTR/TMA. I see that they have this in the IRL ATIS. Would be nice being able to include this on Vatsim as well.

If you have a Copy of the atis, please post it here (or write down what you hear).

Will look into it eventually.

**Comment by Atriusftw** [comment]
> > `DANGER AREA, D, 3 5 4 LEKSDALEN` is currently active within ENVA CTR/TMA. I see that they have this in the IRL ATIS. Would be nice being able to include this on Vatsim as well.
> 
> If you have a Copy of the atis, please post it here (or write down what you hear).
> 
> Will look into it eventually.

```
ENVA ATIS Z 1420Z D-ATIS EXP ILS, OR, RNP APCH RWY27 RSCD 1144Z RWY NR% DRY RWYCC 6 TRL FL90 FOR CLEARANCE AND START-UP, CONTACT TWR, 1 1 9 ' 4. DANGER AREA, D, 3 5 4 LEKSDALEN, IS ACTIVE, 4000 FT. DANGER AREA, D, 3 6 5 GISKAAS, IS ACTIVE, GND, TO FL 1 3 0. WS WRNG, 0 3, VALID. SIGMET, M, 0 2, AND U, 0 1, VALID. WIND VRB 02KT MAX13KT CAVOK T08 DP02 QNH 0986HPA TEMPO 24018G28KT RMK WIND 670FT 00000KT CONFIRM ATIS Z 
```

**Comment by marud94** [comment]
Example of correct liquid template, courtesy of @Adrian2k 

`{% if vars.custom.advdeice %} ADVICE IF DE-ICE IS REQUIRED ON FIRST CONTACT WITH ATC {% endif %}`

**Comment by marud94** [comment]
The SNOWTAM ATIS functions are implemented by dev. 
D354 and D365 is added to our ATIS format, subject to availability on atis.adbj.no.

Since all is done I'm closing the issue. If anything else should be added at a later stage a new issue can be created.

**Comment by Atriusftw** [comment]
> The SNOWTAM ATIS functions are implemented by dev. D354 and D365 is added to our ATIS format, subject to availability on atis.adbj.no.
> 
> Since all is done I'm closing the issue. If anything else should be added at a later stage a new issue can be created.

Does this mean that every D-zone needs to be manually added as a liquid template with a unique parameter?

**Comment by marud94** [comment]
> > The SNOWTAM ATIS functions are implemented by dev. D354 and D365 is added to our ATIS format, subject to availability on atis.adbj.no.
> > Since all is done I'm closing the issue. If anything else should be added at a later stage a new issue can be created.
> 
> Does this mean that every D-zone needs to be manually added as a liquid template with a unique parameter?

Yes. I however can't imagine it would be that many we would consider adding. Those at Værnes are military areas on ground used as shooting ranges in close proximity to aircraft operations.
