### ISSUE TITLE
ENGM holding point GANA established

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#326]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/f003e62c-cec2-4088-bb8a-f21cef9a0dcb)

**Comment by Adrian2k** [comment]
It is in the sectorfile already? Been for a while

**Comment by meltinglava** [comment]
false positive indeed.
