### ISSUE TITLE
DCL not working

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/ENOR-Sectorfile#328]
Jeg er på ENNS. Får CPDLC til å funke, men sliter med DCL også. I mitt tilfelle får jeg requesten, men ingen lister gir meg mulighet å svare som DCL, den tror det er bare vanlig clearance. Stasjonen min er på hoppie-listen ja

Jannik har samme issue.

![image2](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/2505044/2f4ea94b-8848-445b-9829-bc4345d6e8e2)
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/2505044/a3f3837c-43de-4c77-804f-d6511c5b68aa)

**Comment by Adrian2k** [comment]
Jeg vet at for den clearance window så ble det byttet over til en ny "funksjon" i dep list pga en topsky oppdatering.

Først glemte vi å inkludere lists.txt filen i update-only pakka men den ble inkludert nå i den siste oppdateringa. Spørsmålet blir jo om filen faktisk ble overskrevet eller ikke.

@blt950 lar du oppdateringen overskrive de inkluderte settingsfilene, eller har du personaliserte filer som overstyrer? Hvis så, kan du prøve å overskrive lists.txt filen med den som er i sektorfila og prøve? Var dette et engangstilfelle, eller skjedd flere ganger?

Jeg har ikke selv brukt PDC på en mnd´s tid, men vet at det funka rett før vi oppdaterte da jeg testet oppdatering relatert til ENGM. Satt da med clean install av sektorfilen.

I hovedsak Jakob som jobber med TopSky relaterte ting, så mulig at han har noe input her også @morettio

**Comment by blt950** [comment]
Jeg lar sektorfiloppdateringen alltid skrive over evt endringer jeg har gjort. Skjedd 2 ganger hos meg, men nå har jeg bare slått på DCL to ganger også. 

Jannik har som nevnt over også hatt samme utfordring i nyeste sektorfil. Lurer på om det er flere i den Discord tråden som slet med det. Sjekk tråder i controllers

**Comment by morettio** [comment]
Har problemet fikset seg? Prøvd med ny nedlasting? List.txt manglet i siste oppdatering. @blt950

**Comment by blt950** [comment]
Jeg kan laste ned siste list.txt herifra neste gang jeg skal kontrollere så skal jeg si ifra hvordan det gikk.

**Comment by morettio** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/59777657/7ff237f9-3788-401f-9a2c-4313f11df204)
Problemet var i listen til Daniel. List.txt som følger sectorfil er riktig.
