### ISSUE TITLE
AIP SUP - ENEV RNP AR new approaches

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#331]
https://avinor.no/globalassets/_microsite/ais-portal/aip-sup/en_sup_a_2024_001_en.pdf

**Comment by Adrian2k** [comment]
STAR:ENEV:17:CONGE·RNP·W:CONGE EV524 EV523 EV520 ;  Combiner=ENEV1/AH | ID=17_CONGE_H-W
STAR:ENEV:17:FINJO·RNP·E:FINJO EV522 EV521 EV520 ;  Combiner=ENEV1/AH | ID=17_FINJO_H-E

STAR:ENEV:35:MELLE·RNP·W:MELLE EV726 EV725 EV720 ;  Combiner=ENEV5/AH | ID=35_MELLE_H-W
STAR:ENEV:35:LEGLU·RNP·S:LEGLU STETI EV722 EV721 EV720 ;  Combiner=ENEV5/AH | ID=35_LEGLU_H-S
STAR:ENEV:35:MAXED·RNP·S:MAXED STETI EV722 EV721 EV720 ;  Combiner=ENEV5/AH | ID=35_MAXED_H-S
STAR:ENEV:35:UFFET·RNP·E:UFFET EV724 EV723 EV720 ;  Combiner=ENEV5/AH | ID=35_UFFET_H-E
