### ISSUE TITLE
Unable to see assigned speed in tags that is while in next sector

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#332]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/d7910074-31c6-4645-87a5-b4175c723161)
Find myself wanting to see it for planning purposes.

**Comment by Adrian2k** [comment]
Just verify which tag family you are using @meltinglava

**Comment by meltinglava** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/ab53b972-55ee-493e-b0c8-e7e48c132c22)

**Comment by morettio** [comment]
Taggen skal ikke endre seg selv om den er assumet hos en annen CJI.
GS står forran ADES i alle FDB taggene.

Så taggen som vist på bildet viser ikke feilen eller manglen.

Fint om du kan forklare litt mer hva du ønsker. @meltinglava

**Comment by krislarsen** [comment]
Tror det @meltinglava  vil frem til her å ha muligheten til å se assigned speed i tag untagged. I detailed pleier det å være mellom CFL og STAR og der ser det ut til at det er et tomrom når tagen er untagged.

**Comment by Adrian2k** [comment]
Høres jo meningsfult ut at man skal kunne se assigned speed i tag uavhenig om man eier taggen eller ei?

**Comment by morettio** [comment]
Kan legge det inn :)

**Comment by morettio** [comment]
Added to Main, Release next sectorfile.
