### ISSUE TITLE
Adding custom aliases

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#333]
Form my understanding the only way to achieve this today is to edit the `alias.txt` file that comes with the sector files, which works fine until updating which overwrites the file.

Is there other way to create our own aliases, or is this something that could be suggested to the ES developer?

**Comment by Adrian2k** [comment]
The alias'es is controlled in GNG and the file is generated each time with a GNG release.
You can always make new requests, it is currently @marud94 who manages the alias part of the sectorfile.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/f33a775d-8f19-4e5c-9fa3-6a97b5abeb73)

**Comment by Atriusftw** [comment]
Gotcha. I lost my custom aliases, but one i remember which is really useful is:

`.respawn You have spawned on an occupied stand. I recommend respawning on stand $1 to avoid any issues. The site https://stands.vatsim-scandinavia.org is useful to check available stands.`

**Comment by krislarsen** [comment]
> Gotcha. I lost my custom aliases, but one i remember which is really useful is:
> 
> `.respawn You have spawned on an occupied stand. I recommend respawning on stand $1 to avoid any issues. The site https://stands.vatsim-scandinavia.org is useful to check available stands.`

See no issue adding this. I'm sure we'll add this.

**Comment by marud94** [comment]
Added the command rephrased with the commands .standocc and .respawn as seen below.

`.standocc .msg $aircraft You have connected on a occupied stand. I recommend moving to stand $1 to avoid any issues. Available stands can also be found at stands.vatsim-scandinavia.org.
.respawn .msg $aircraft You have connected on a occupied stand. I recommend moving to stand $1 to avoid any issues. Available stands can also be found at stands.vatsim-scandinavia.org.`

Closing the issue now, for other suggestions/wishes a new issue can be opened.

**Comment by BlomsenSr** [comment]
@marud94 de to aliasene er jo prikk like.
mener jeg leste en kommentar om at respawn var tiltenkt fly som logget på, på en rullebane eller lignende?

Er det ikke litt overkill med to alias på samme?

**Comment by marud94** [comment]
> @marud94 de to aliasene er jo prikk like. mener jeg leste en kommentar om at respawn var tiltenkt fly som logget på, på en rullebane eller lignende?
> 
> Er det ikke litt overkill med to alias på samme?

Tanken er bare å gi en mulighet for å bruke forskjellig kommandoer, om det er flere som har .respawn for eksempel. Selvfølgelig mulig å endre slik at .respawn sender PM til fly om å flytte seg til stand hvis ønskelig
