### ISSUE TITLE
Possible mismatch on Euroscope and AIP, EVENES approtch fix

### ISSUE THREAD

**Issue by vegsor** [Vatsim-Scandinavia/ENOR-Sectorfile#335]
There seems to be a mismatch of tha cordinates on the approch to ENEV
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/134779268/c52422ed-a045-4d2f-9099-07f2b3505351)
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/134779268/67717aac-d701-4907-b7d0-0c6bc7d43ca8)

**Comment by Adrian2k** [comment]
No it is not - the default approach for 35 is based on RNP-Z
The attached photo is for the RNP-X which requires RF and authorization to be used.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/844a3e9e-e736-4268-a918-e663c1b958ec)
