### ISSUE TITLE
No "omni" selectable for ENHK

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#336]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/79529337/7c6ac111-9978-458f-8493-4a925952877e)

OMNI 2A and OMNI 2B is available.

**Comment by Adrian2k** [comment]
Solved.

SID:ENHK:11:ENHK2A:ENHK ; Combiner=ZZZZ1/2 | ID=11_ENHK2A
SID:ENHK:29:ENHK2B:ENHK ; Combiner=ZZZZ1/2 | ID=29_ENHK2B
