### ISSUE TITLE
ENGM ACFT STAND 47 REESTABLISHED

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#346]

**Comment by Adrian2k** [comment]
Anyone knows if this is visible in any sceneries?

**Comment by Atriusftw** [comment]
Stand 47 is included in the Aerosoft scenery for MSFS.

**Comment by Adrian2k** [comment]
Could possibly be readded as a stand, but without any automatic stand assignment for now.

**Comment by Atriusftw** [comment]
Self assigning this as a trivial task to begin with :)
