### ISSUE TITLE
ENSG ATIS should be Sogndal instead of Haukasen

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#347]

**Comment by janfelhut04** [comment]
When creating the ATIS it says Expect ILS approach for 06 which isn't correct. I guess it should be LOC or RNP

**Comment by marud94** [comment]
Had to remove and readd the airport due to DB error. 06 has RNP A as default now, 24 has ILS. Name set to Sogndal.
