### ISSUE TITLE
Adjust on ground filter?

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#351]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/a282729a-3973-45ed-bec2-5111e022c677)

Currently the issue is that helicopters flying slowly is being detected as on ground due to EuroScope logic.

Reduce to 35-40knots?
Reduce the altitude? What is our highest airport?

**Comment by meltinglava** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/e6a513c2-f5c9-4eec-a281-1ca5b85df2df)
Guess we can round up to 2800 to take pressure difference errors into account.

**Comment by Adrian2k** [comment]
ENRO is the cloest with radar coverage

**Comment by Adrian2k** [comment]
Can probably get away by setting it to 1000ft and 30kts - adjust it higher if needed.

On airports such as ENSG and ENBL it should be quite impressive to taxi to taxi anything faster than 20knots - also ENSG it outside of radar coverage.

**Comment by Adrian2k** [comment]
Adjusted to 2400ft 35kts.
