### ISSUE TITLE
Radar target differences

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#354]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/6aff0a62-32e1-40b9-9f09-98efc31c07eb)

All tracks should be filled square

**Comment by morettio** [comment]
Changed Tag Symbols, Rectangular shape for Mode C (Non DAP) and Diamant for Mode S (DAP)

**Comment by Adrian2k** [comment]
> This where changed last sectorfile release to see which tag was mode S. _Changed Tag Symbols, Rectangular shape for Mode C (Non DAP) and Diamant for Mode S (DAP)_

This is not a feature IRL according to Martin.
