### ISSUE TITLE
PDC alias - issues with atis information

### ISSUE THREAD

**Issue by marud94** [Vatsim-Scandinavia/ENOR-Sectorfile#369]
Won't get atiscode with multiple atis at one airport. Plan to remove atis from PDC.

**Comment by meltinglava** [comment]
This might be something that is fixed on newer euroscope releases, as there was added support for dual ATIS. We should remember to check this when we upgrade in the future.

**Comment by marud94** [comment]
Does not work on 3.2.3 at least. Not mentioned anywhere in documentation either. Will look more into it when able

**Comment by marud94** [comment]
Removed ATIS in PDC for now, can update if supported in ES later
