### ISSUE TITLE
ENOS + ENOR sector changes proposal

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#370]
Following ENOS changes has been proposed:

ENOS_CTR: Change main sector to sector 5
ENOS_4_CTR: New sector, only covering S3+S4
ENOS_8_CTR: Demote as a primary sector, only to be covering S8 regardless of other sectors being online.

Reason:
Sector 5 is rarely used and can be used as a main sector instead. This allows us to have a S3+S4 split that can be used during Oslo Monday events. IRL sector 3 and 4 is rarely split.
Most controllers believe ENOS8 only covers S8, which is not true. This change will simply allign with peoples expectations of ENOS8. Also no need for 3 main ENOS sectors

ENOR Suggestion:
Establish ENOR_SC_CTR which will cover the old ENOR_S_CTR's area.

**Comment by srekdal** [comment]
I agree with this proposal. It makes sense.

The available splits would then be:
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/59778165/3d347f29-d275-43cb-9b13-cd538d0c5473)

**Comment by Adrian2k** [comment]
To be implemented:

- Implement ENOR_SC_CTR covering ENOS+ENSV+ENBD-S
- Change ENOS_CTR from 4R to 5R
- Implement ENOR_4_CTR as sector, covering 4+3
- ENOS_8_CTR to only cover S8
- ENSV_E_CTR to only cover S13+S14

To do:

- [ ] Make changes in GNG
- [ ] Update login profiles
- [ ] Update topsky relevant files (CPDLC stations, frequency display by border)
- [X] Coordinate LOA Scottish
- [ ] Coordinate LOA Sweden
- [ ] Coordinate LOA Denmark
- [ ] Update VATspy sectors

**Comment by Adrian2k** [comment]
@marud94 VATATIS changes:
Reassign ENOS_CTR to freq 127.250 (current yENOS_5_CTR)
Create new ENOS_4_CTR sector, freq 118.875
Create new ENOR_SC_CTR sector, freq 134.515
Remove ENSV_E_CTR


ENBR, ENZV, ENSG, ENBL, ENFL, ENHD, Ekofisk + Tampen - Remove ENSV_E_CTR

ENGM -Remove ENOR_8_CTR
ENCN - Remove ENOS_5_CTR
ENTO/ENRY - Remove ENOS_8_CTR & add ENOR_4_CTR (before ENOR_CTR)

ENBR, ENZV, ENSG, ENBL, ENFL, ENHD, Ekofisk + Tampen, ENGM, ENCN, ENTO, ENRY, ENRO, ENVA, ENOL, ENKB, ENML, ENAL - Add ENOR_SC_CTR (before ENOR_CTR)


ENOS_CTR 118.875 should not be touched until AIRAC day.
ENOS_4_CTR probably not smart to add until ENOS_CTR has been changed.

All other sectors safe to do now.

**Comment by Adrian2k** [comment]
@morettio 
Topsky:
All instances of 4R must be changed to 5R.
Add frequency display for new 4R sector in area S3+S4
Add frequency display for new ENOR_SC_CTR sector, ID: NC
Add CPDLC station for NC

Anything else?

**Comment by krislarsen** [comment]
> To be implemented:
> 
> * Implement ENOR_SC_CTR covering ENOS+ENSV+ENBD-S
> * Change ENOS_CTR from 4R to 5R
> * Implement ENOR_4_CTR as sector, covering 4+3
> * ENOS_8_CTR to only cover S8
> * ENSV_E_CTR to only cover S13+S14
> 
> To do:
> 
> * [ ]  Make changes in GNG
> * [ ]  Update login profiles
> * [ ]  Update topsky relevant files (CPDLC stations, frequency display by border)
> * [x]  Coordinate LOA Scottish
> * [ ]  Coordinate LOA Sweden
> * [ ]  Coordinate LOA Denmark
> * [x]  Coordinate with Reykjavik
> * [ ]  Update VATspy sectors
> * [ ]  Update VATATIS

Sweden and Demark is informed and has "approved" changes, though LoA change still WIP.

**Comment by marud94** [comment]
(For own memory)
VATATIS changes:
- [ ] Reassign ENOS_CTR to freq 127.250 (current yENOS_5_CTR)
- [ ] Create new ENOS_4_CTR sector, freq 118.875
- [ ] ENTO/ENRY - add ENOR_4_CTR (before ENOR_CTR)

NOT BEFORE NEW SECTORFILE IS READY

**Comment by morettio** [comment]
Topsky Done, It needs testing after sector release.

**Comment by Adrian2k** [comment]
GNG changes done (not tested).
VATspy changes done and sent for review.

Pending:
Topsky testing @morettio (?)
VATATIS @marud94

**Comment by marud94** [comment]
> GNG changes done (not tested). VATspy changes done and sent for review.
> 
> Pending: Topsky testing @morettio (?) VATATIS @marud94

VATATIS completed

**Comment by Adrian2k** [comment]
@morettio MVA maps not working for ENOR_SC

**Comment by morettio** [comment]
> @morettio MVA maps not working for ENOR_SC

Done @Adrian2k
