### ISSUE TITLE
SUP addition to alias file

### ISSUE THREAD

**Issue by DotWallop** [Vatsim-Scandinavia/ENOR-Sectorfile#372]
I propose to add some basic SUP-related alias entries in order to standardize the wallop text and give enough information to the handling supervisor, without imposing too much workload on the controller. The alias entries are for the most time-critical and most often occurring SUP reports.
For ease of reference, the shorthand will be prefixed with _sup_, the aliases are named so they are easy to memorize, and the content is short and concise.

.supnordo .wallop Callsign $1 is unresponsive in controlled airspace.
.supnoclr .wallop Callsign $1 is moving without clearance.
.suprwyspawn .wallop Callsign $1 has spawned on an active runway.
.suphotmic .wallop Callsign $1 is hot-micing on active frequency ($com).
.supnoob .wallop Callsign $1 does not meet the minimum pilot competency requirements and SUP intervention is requested.

**Comment by marud94** [comment]
Added to Alias and documentation on the wiki as well.
