### ISSUE TITLE
ENZV_A_APP

### ISSUE THREAD

**Issue by TryFanGamer** [Vatsim-Scandinavia/ENOR-Sectorfile#373]
Sola Arrival does not have any airspace not sure what the split is supposed to look like. Is this a issus or not? maby something to look in to
![2024-04-27-1410z-42s_EuroScope_v3 2c](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/101999533/0d966493-82e2-4f31-86ae-7ab33946eaf4)

**Comment by krislarsen** [comment]
This is intentional. Sola Arrival does have only responsability for arrival, hence no logical way to define area. Therefore it’s shared airspace with ENZV_APP. @Adrian2k can respond if it should look like that in a technical perspective

**Comment by TryFanGamer** [comment]
okay. How do this work when Polaris is handling of tags, then?

**Comment by Adrian2k** [comment]
No airspace is being assigned for two reasons:

1. To purposely illustrate that you do not "own" any airspace and have to share airspace with ENZV_APP.
2. There is no logical way of giving ARR any airspace without it breaking other EuroScope logics (EuroScope does not like duplicate airspace definitions).

Polaris will have to manually handoff traffic to ENZV ARR (F4 + ZER) if both are online.

ENZV_A_APP is added as a guest for ENZV ARR's in the TMA, which means EuroScope will not prompt you to handover traffic to ENZV_APP, but instead to ENZV_TWR just as it would if you owned the airspace. (Only for ENZV arrivals, not ENHD).

Noticed that some of the guest entries was set up incorrectly, so it will be corrected with the next sectorfile update.

![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/7b354fd0-422e-4870-b9b9-5d7eb6e8dd96)
