### ISSUE TITLE
COPX altitude ENTC SIDs

### ISSUE THREAD

**Issue by marud94** [Vatsim-Scandinavia/ENOR-Sectorfile#376]
DLH5W ENTC - EDDF on AMIMO3B (no DCT), climb altitude gives cruise an not FL190 which is max permittable for APP.

**Comment by marud94** [comment]
SIDs currently have COPX climb to FL180, but can be raised to FL190 as TC TMA is up to FL 195

**Comment by krislarsen** [comment]
Adjusted in GNG, will be pushed with new Sectorfile update.
