### ISSUE TITLE
GRpluginStands incorrect codes at ENBR

### ISSUE THREAD

**Issue by Azchk** [Vatsim-Scandinavia/ENOR-Sectorfile#378]
CODE is incorrect for ARC E stands and GA parking which is ARC B due to Taxiway B width south of U

Suggestions:
[`//STAND 1
STAND:ENBR:1:N060.16.55.890:E005.13.34.920:20
PRIORITY:-1
WTC:MH
CODE:F`
Change to
`//STAND 1
STAND:ENBR:1:N060.16.55.890:E005.13.34.920:20
PRIORITY:-1
WTC:MH
CODE:E`]

[`//STAND 10
STAND:ENBR:10:N060.17.10.300:E005.13.36.400:20
PRIORITY:-2
BLOCKS:9,11
CODE:E:E`
Change to
`//STAND 10
STAND:ENBR:10:N060.17.10.300:E005.13.36.400:20
PRIORITY:-2
BLOCKS:9,11
CODE:E`]

[`//STAND 24
STAND:ENBR:24
COORD:N060.17.17.469:E005.13.31.329
COORD:N060.17.16.896:E005.13.30.768
COORD:N060.17.16.060:E005.13.32.858
COORD:N060.17.16.251:E005.13.34.697
COORD:N060.17.17.975:E005.13.35.427
COORD:N060.17.18.459:E005.13.34.192
COORD:N060.17.17.469:E005.13.31.329
BLOCKS:23,25:D
USE:A
CODE:C
NOTADEP:EN`
Change to
`//STAND 24
STAND:ENBR:24
COORD:N060.17.17.469:E005.13.31.329
COORD:N060.17.16.896:E005.13.30.768
COORD:N060.17.16.060:E005.13.32.858
COORD:N060.17.16.251:E005.13.34.697
COORD:N060.17.17.975:E005.13.35.427
COORD:N060.17.18.459:E005.13.34.192
COORD:N060.17.17.469:E005.13.31.329
BLOCKS:23,25:D
USE:A
CODE:E
NOTADEP:EN`]

[`//STAND 27
STAND:ENBR:27
COORD:N060.17.22.454:E005.13.30.702
COORD:N060.17.22.514:E005.13.28.665
COORD:N060.17.21.198:E005.13.28.385
COORD:N060.17.20.832:E005.13.31.668
COORD:N060.17.20.926:E005.13.33.024
COORD:N060.17.21.782:E005.13.33.302
COORD:N060.17.22.454:E005.13.30.702
BLOCKS:26,28:D
USE:A
CODE:C
NOTADEP:EN`
Change to
`//STAND 27
STAND:ENBR:27
COORD:N060.17.22.454:E005.13.30.702
COORD:N060.17.22.514:E005.13.28.665
COORD:N060.17.21.198:E005.13.28.385
COORD:N060.17.20.832:E005.13.31.668
COORD:N060.17.20.926:E005.13.33.024
COORD:N060.17.21.782:E005.13.33.302
COORD:N060.17.22.454:E005.13.30.702
BLOCKS:26,28:D
USE:A
CODE:E
NOTADEP:EN`]

[`//GA-PARKING
STAND:ENBR:GA:N060.17.58.027:E005.13.35.167:40
AREA
USE:P
WTC:L`
Change to
`//GA-PARKING
STAND:ENBR:GA:N060.17.58.027:E005.13.35.167:40
AREA
USE:P
WTC:L
CODE:B`]

**Comment by meltinglava** [comment]
> STAND 1

Is probably set to that there is not an error every time a CAT F goes in.

> STAND 10

This is syntax to describe only to assign to E not E or less. This makes sence as we want the remaniding to get stand 11 / 9 instead.

These 2 should probably stay as is.
