### ISSUE TITLE
Covnvert all GRPlugin stands to polygons

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#383]
Sceneries does have too much variety in them, making stands not show as occupied.
Would be better to convert all to all to polygons instead.

Example from ENBR
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/1202d2c5-0f66-4ac9-a276-178c9152fa9a)

**Comment by Adrian2k** [comment]
@Atriusftw I have previously done this by creating polygons in QGIS and converting the coordinates with https://webtools.kusternet.ch/geo/coordinatesconverter

**Comment by Atriusftw** [comment]
Looks like most of the stands are already polygons. Exceptions are some ENGM and ENBR stands, which i assume should stay as custom areas?
