### ISSUE TITLE
ENOR_SC missing vispoints

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#390]
Vispoints not defined

**Comment by morettio** [comment]
And .vis is also added.

**Comment by Adrian2k** [comment]
Reopened, this is not topsky related.
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/daae447c-aae6-4f61-8155-8d2c8fefd0f4)

**Comment by Adrian2k** [comment]
Fixed awhile ago
