### ISSUE TITLE
Change request: Remove SSR from untagged datablock, add warning for 7600/7700 to untagged datablock.

### ISSUE THREAD

**Issue by Eseem91** [Vatsim-Scandinavia/ENOR-Sectorfile#393]
The untagged datablock of correlated aircraft includes the SSR code. I struggle to see a benefit, and it takes up screen space, so suggest it be removed.

Currently the uncorrelated tags do not show a warning for radiofail/comfail. Suggest adding this. Note that it seems the uncorrelated tags might require a fixed user colour assignment to show as red 

Benefits from this setup:
- If there is no correlation, the pilot set squawk will show in the callsign line anyway. Conspicuity squawks can still be seen, i.e. IFR/VFR/police/hems/glider. No info is lost.
- If there is correlation, the squawk is irrelevant and will not show in the datablock, only the callsign.
- If an emergency squawk is set, it will show the flag regardless. 

Example file, with suggested changes made to **NATCON Real family**: 
[Tags.txt](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/files/15461753/Tags.txt)
(to make uncorrelated flags red, make User 6 a red color in Symbology Settings - Datablock)

Example picture, with current setup on the left and suggested change on the right:
![old vs new tags](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/170978922/36a3263c-afc9-4ef0-841c-25f02149c7e3)

**Comment by morettio** [comment]
Added tags from S.Rekdal with change to all FDB tags.
