### ISSUE TITLE
sector ownership BR CTR + SO TIZ with ENOR_SC + ENSV_14

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#394]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/17087998/d72423e8-b24e-4d25-836d-cd8fec2283b1)

**Comment by Adrian2k** [comment]
Fixed, require update of vatglasses.

**Comment by meltinglava** [comment]
ref: lennycolton/vatglasses-data#273
