### ISSUE TITLE
Remove waypoint VAKIR

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#398]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/1478937/0b75bcd1-a8c9-40de-b583-431364cafc1b)
This was found in a valid flight plan to EYVI.

According to current AIRAC, the waypoint `VAKIR` is only present in Lithuania.

**Comment by Adrian2k** [comment]
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/8140149c-8a87-4e68-8442-f7fb9387a372)
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/35482228/700d7a5b-7723-46b5-a9e2-4a16ba3f515c)

Most likely unable to resolve, reported to GNG developers
