### ISSUE TITLE
ENBO GND

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#399]
Don't know when AVINOR changed this, but Bodø Ground has been removed AIP, but is still a log-on position in EuroScope.
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/b47590b8-a88e-429e-9344-139a5f440d88)
![image](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/assets/89723211/e6ca5feb-2eb6-4eb9-b7f0-5ba6d9f87970)

**Comment by Adrian2k** [comment]
26 JAN 2024 apparantly in jeppesen charts

**Comment by Adrian2k** [comment]
- [ ] Remove airspace
- [ ] Remove position
- [ ] Remove login profile
- [ ] Remove in CC
- [ ] Remove from S1 endorsement?
- [ ] Remove AFV station

**Comment by Adrian2k** [comment]
Remaining tasks to be done at sector file release

**Comment by Azchk** [comment]
Found out it still exists in the CENOR FLIP, so maybe it's only for MIL use?

Still probably best to remove it.![Screenshot_20240904-084530_Drive.jpg](https://github.com/user-attachments/assets/5259ac33-c57a-4de5-b00c-3a79b6affd95)

**Comment by Adrian2k** [comment]
We refer to AIP Norway only
