### ISSUE TITLE
ENEV_TWR missing in AfV database

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#410]
118.000

**Comment by vegsor** [comment]
think its the same with ENDU 118.100

**Comment by Adrian2k** [comment]
I have added ENEV_TWR and ENDU_TWR now, please verify issue is resolved

![image](https://github.com/user-attachments/assets/56ecf886-bb32-455c-ad3f-6f2f956ee641)
![image](https://github.com/user-attachments/assets/3fe06dc2-7cf0-4b17-91cb-a7d7f0fa4e59)

**Comment by Atriusftw** [comment]
Confirming both available via AfV now. Thank you :)
