### ISSUE TITLE
Change ENGM_Q_GND to ENGM_P_GND?

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#411]
It is more of a planner role and pilots are more familiar with _P_ than _Q_

There is some places where these switch such as in AFV config where half of the places ENGM_Q_GND is used and the other half ENGM_P_GND.

Can we standardize this to one use? I suggest ENGM_P_GND
We can still use the name sequencer internally/between ATC, this is only a suggestion to change the logon to only one option.

@krislarsen opinion?

**Comment by morettio** [comment]
GO for it!

**Comment by krislarsen** [comment]
> @krislarsen opinion?

I have always preferred it as a planner position. So I agree with this implementation

**Comment by Adrian2k** [comment]
Following wiki pages needs updating:
https://wiki.vatsim-scandinavia.org/books/software/page/cdm-manual
https://wiki.vatsim-scandinavia.org/books/norwegian-airports-charts/page/engm-oslo-lufthavn

**Comment by krislarsen** [comment]
> Following wiki pages needs updating: https://wiki.vatsim-scandinavia.org/books/software/page/cdm-manual https://wiki.vatsim-scandinavia.org/books/norwegian-airports-charts/page/engm-oslo-lufthavn

Both updated now
