### ISSUE TITLE
All things to be done in AFV

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#412]
Missing:
- [x] ENGM_ICE_GND
- [x] ENOL_APP
- [x] ENOL_A_APP
- [x] AFIS Helgeland
- [x] Offshore HFIS?
- [x] ENNA_APP
- [x] ENBD_H_CTR

**Comment by Adrian2k** [comment]
Remove:

- [ ] ENNA TWR
- [ ] ENBO GND

**Comment by Adrian2k** [comment]
> Unable to use Trackaudio at ENVD, AFV works. in Addition, no one was able to listen to my freequenzy on AFV

#469

**Comment by Adrian2k** [comment]
ENOS S5 - Bad reception ENNO

**Comment by Atriusftw** [comment]
ENBR_W_APP - Bad reception at ENSO

**Comment by Adrian2k** [comment]
All issues above fixed
