### ISSUE TITLE
Add corridors west of Sola and Flesland TMA to lower limit asr

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#414]
N623 airway (20NM wide corridor) FL95-195 (Class D)
```
N061.32.50.000	E000.00.00.000
N060.53.51.997	E003.53.47.749

N060.52.50.187	E000.00.00.000
N060.17.02.599	E003.28.20.485
```

P600 airway (20NM wide corridor) FL95-195 (Class D)
```
N058.08.12.025	E003.14.14.965
N058.11.04.600	E003.45.58.022

N058.49.06.259	E003.22.09.821
N058.38.25.982	E002.24.34.227
```

![image](https://github.com/user-attachments/assets/9dbd43c7-0ab3-4744-afbf-0eafa0750677)

**Comment by Adrian2k** [comment]
Any preference of color? These was marked with a different color IRL?

**Comment by Sanderli25** [comment]
> Any preference of color? These was marked with a different color IRL?

I would prefer the same white colour as lower limit as it will be in this .asr :)

**Comment by Adrian2k** [comment]
Lines added to `CTA - Lower limits - ENSV AoR` now
Pending: Text labels

**Comment by Sanderli25** [comment]
Corridor width 10NM. Will send new coordinates shortly.

**Comment by Sanderli25** [comment]
N623 airway (10NM wide corridor) FL95-195 (Class D)
```
N061.07.51.941	E000.00.00.000
N060.29.04.700	E003.48.09.819

N061.17.51.941	E000.00.00.000
N060.38.57.368	E003.50.24.479
```

P600 airway (10NM wide corridor) FL95-195 (Class D)
```
N058.19.38.453	E002.55.54.141
N058.25.17.674	E003.36.34.337

N058.27.10.501	E002.43.29.820
N058.34.45.495	E003.30.19.139
```
![image](https://github.com/user-attachments/assets/7c7e0431-d402-409a-815d-d1d370aab2c6)

![image](https://github.com/user-attachments/assets/81be1028-1526-4cdb-8bad-5b30ae08b23e)

**Comment by Adrian2k** [comment]
**Following sectors created:**
ENOR·S15-LOWER2-N623·095·195
ENOR·S11-LOWER2-P600·095·195

FL95 text labels added at
COORD:N060.53.11.074:E001.58.16.410
COORD:N058.27.22.990:E003.08.58.657
