### ISSUE TITLE
vats.im link til ENBR og ENTC

### ISSUE THREAD

**Issue by Azchk** [Vatsim-Scandinavia/ENOR-Sectorfile#416]
https://vats.im/ENVA og https://vats.im/ENGM linker til den relevante siden på https://wiki.vatsim-scandinavia.org/books/norwegian-airports-charts/

Jeg skulle ønske at dette også gikk for ENBR og ENTC

https://vats.im/ENTC ser ut til å linke til http://santa.vatsim-scandinavia.org/tromso.php som ikke fungerer.

**Comment by Adrian2k** [comment]
Assigning @krislarsen for this

**Comment by Atriusftw** [comment]
Note that we have our own URL shortener service on the `vatsca.org` domain. Web department can assist with adding new URLs to this.

**Comment by blt950** [comment]
I've created links for you guys

https://vatsca.org/ENBR
https://vatsca.org/ENTC
https://vatsca.org/ENGM
https://vatsca.org/ENBR

Note: case sensitive

**Comment by Atriusftw** [comment]
> I've created links for you guys
> 
> https://vatsca.org/ENBR https://vatsca.org/ENTC https://vatsca.org/ENGM https://vatsca.org/ENBR
> 
> Note: case sensitive

![906w88](https://github.com/user-attachments/assets/42671fcc-38bb-4ab9-ae76-68c6574e25b6)

**Comment by blt950** [comment]
https://vatsca.org/ENVA

**Comment by krislarsen** [comment]
Looks to me that someone have been in advance and fixed this. Closed as compleated

**Comment by Atriusftw** [comment]
> Looks to me that someone have been in advance and fixed this. Closed as compleated

Should we add it to the login profiles within sector files, though?

**Comment by krislarsen** [comment]
> > Looks to me that someone have been in advance and fixed this. Closed as compleated
> 
> Should we add it to the login profiles within sector files, though?

It is a different issue though. If it is a wanted request, feel free to open it as an new issue.
