### ISSUE TITLE
Edit SSR for NATO QRA Range

### ISSUE THREAD

**Issue by BlomsenSr** [Vatsim-Scandinavia/ENOR-Sectorfile#417]
Since NATO QRA has changed from ENBO to ENEV, they have changed default callsigns to
EM.

Aircraft tasked on Air Defence missions will have the following callsigns, related to the base they are taking off from. Exception to this is live QRA from Evenes using callsigns EM 01-04 regardless of departing base.
ENAN – EA 01-77
ENBO – EG 01-77
ENDU – EE 01-77
ENNA – EH 01-77
ENEV – EM 01-77
ENOL – HL 01-77
ENRY - HA 01-77
ENZV- HE 01-77
ENGM- HG 01-77
(Numbers 8 and 9 will not be used)

**Comment by morettio** [comment]
We can not add all the callsigns to the SSR list, then there will be over 2000 lines of code to get the correct SQ. I will add EM 01 - 04 instead of EG from ENBO since it is already in the list.
