### ISSUE TITLE
Remove ETA from flightplan list?

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#421]
Who ever uses this item? Why do we have it?

Removing it will make our lists a little bit smaller.
Anything else that can be removed from the lists?

**Comment by morettio** [comment]
We can hide it, and then anyone who is using ETA can use it as needed.

**Comment by morettio** [comment]
ETA is hidden in the Sector Inn and Out list.
