### ISSUE TITLE
Change of OMNI(H) dep at Sola

### ISSUE THREAD

**Issue by janfelhut04** [Vatsim-Scandinavia/ENOR-Sectorfile#426]
Change OMNI3X (18), OMNI3Y (36), OMNI1Q (10) and OMNI1Z (28) 
ENZV3X - ENZV3Y - ENZV1Q - ENZV1Z
![Screenshot 2024-08-15 195619](https://github.com/user-attachments/assets/ed06e91d-03fc-4bfc-ad86-362006c466fe)
![Screenshot 2024-08-15 195642](https://github.com/user-attachments/assets/d253fbb8-3d2c-4a8c-8e2c-13414f4f1c20)

**Comment by Adrian2k** [comment]
![image](https://github.com/user-attachments/assets/10807c83-5d33-410c-b0a6-9a90c3d5b44a)

```
SID:ENZV:10:ENZV1Q:ENZV ; Combiner=ZZZZ1/2 | ID=10_ENZV1Q
SID:ENZV:10:ENZV2E:ENZV ; Combiner=ZZZZ1/2 | ID=10_ENZV2E

SID:ENZV:18:ENZV2G:ENZV ; Combiner=ZZZZ1/2 | ID=18_ENZV2G
SID:ENZV:18:ENZV3X:ENZV ; Combiner=ZZZZ1/2 | ID=18_ENZV3X

SID:ENZV:28:ENZV1Z:ENZV ; Combiner=ZZZZ1/2 | ID=28_ENZV1Z
SID:ENZV:28:ENZV2F:ENZV ; Combiner=ZZZZ1/2 | ID=28_ENZV2F

SID:ENZV:36:ENZV2H:ENZV ; Combiner=ZZZZ1/2 | ID=36_ENZV2H
SID:ENZV:36:ENZV3Y:ENZV ; Combiner=ZZZZ1/2 | ID=36_ENZV3Y
```

**Comment by Adrian2k** [comment]
@Sanderli25 OMNI deps or heli deps do not have defined initial climb at ENZV - only setting defined is 6000ft for everything.

OMNI helicopter is 2000ft
OMNI jet/prop is 5000ft
Helicopter RNAV is 2000ft

**Comment by Adrian2k** [comment]
Could not find any documentation in our wiki that needed updating.

So only pending initial climb fix (as above) then issue can be closed as resolved.

**Comment by morettio** [comment]
Added to Topsky Init Climb.

**Comment by Adrian2k** [comment]
> Added to Topsky Init Climb.
> 
> ![image](https://private-user-images.githubusercontent.com/59777657/359617477-11432197-255e-4df6-8125-7d7671dd9e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxODIyMjMsIm5iZiI6MTcyNDE4MTkyMywicGF0aCI6Ii81OTc3NzY1Ny8zNTk2MTc0NzctMTE0MzIxOTctMjU1ZS00ZGY2LTgxMjUtN2Q3NjcxZGQ5ZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDE5MjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MmI4ODU2YzU2MDNkNjQ0ODEwMzQ3ZjE4M2JmMWFlOWY0MDIxMGU1ZTM5ZWM2ODhlZWRiYzdkOGVmNTNhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1_Rui5pcufPbmohpAYWjCNcxpPG-sY4WVy22aqJCMfc)

Missing RNAV heli sids

**Comment by morettio** [comment]
@Adrian2k 
![image](https://github.com/user-attachments/assets/5ff0fcbc-b7e3-4184-9656-6ebbc6c36a76)
