### ISSUE TITLE
Area NUVSA -> Area RIBBE

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#427]
Area NUVSA changed name to Area RIBBE. Change in GNG needed?

**Comment by Adrian2k** [comment]
Yes.
But area is also larger now and I do not have new coordinates for it

**Comment by Adrian2k** [comment]
New coordinates recieved - will fix before next release

**Comment by Adrian2k** [comment]
This is going to be painful to fix..

@Sanderli25 confirm you have fixed the wiki?

**Comment by Sanderli25** [comment]
> This is going to be painful to fix..
> 
> 
> 
> @Sanderli25 confirm you have fixed the wiki?

Wiki fixed

**Comment by Adrian2k** [comment]
![image](https://github.com/user-attachments/assets/517a6dc8-8b7d-43ab-9a5d-61a489c94037)
![image](https://github.com/user-attachments/assets/c8d38866-bcec-4fa0-81b6-d4d1dd035bc8)
