### ISSUE TITLE
HTZ zones changed

### ISSUE THREAD

**Issue by vegsor** [Vatsim-Scandinavia/ENOR-Sectorfile#445]
OLD
![image](https://github.com/user-attachments/assets/215c6084-ca9b-4933-a7cc-9a791b1011cc)
https://ais.avinor.no/no/AIP/View/133/2024-09-05-AIRAC/graphics/484245.pdf
https://ais.avinor.no/no/AIP/View/133/2024-09-05-AIRAC/graphics/494365.pdf

New
![image](https://github.com/user-attachments/assets/b8396298-962e-45fa-9a0b-d20351d8eb33)
https://ais.avinor.no/no/AIP/View/133/2024-09-05-AIRAC/graphics/505282.pdf
https://ais.avinor.no/no/AIP/View/133/2024-09-05-AIRAC/graphics/505280.pdf

Check AIP-AMDT-HTZ documents Amended 05.09.24

**Comment by Adrian2k** [comment]
Dupelicate of #389
