### ISSUE TITLE
Sector exit list different colors

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#446]
![image](https://github.com/user-attachments/assets/990e89c7-3fd7-4897-8804-be659f79f5e4)

FR DCT RWY and STD has different color from the others

**Comment by Sanderli25** [comment]
Color_Redundant=4,194,249

**Comment by morettio** [comment]
I have also added "System_UseAcceptedCoordColor=1" for accepted coordinations (COPN/COPX/PEL/XFL/RTI/TIP).

This setting need to be tested.

**Comment by morettio** [comment]
Can not find any problems. If so we can reopen Issue.
