### ISSUE TITLE
Helicopter Point Boundary STAR at ENBR

### ISSUE THREAD

**Issue by Azchk** [Vatsim-Scandinavia/ENOR-Sectorfile#450]
SECTOR VENIN 2A, SECTOR VENIN 2B
https://ais.avinor.no/no/AIP/View/133/2024-09-05-AIRAC/graphics/449291.pdf
SECTOR UPEPI 1A, UPEPI 1B
https://ais.avinor.no/no/AIP/View/133/2024-09-05-AIRAC/graphics/146141.pdf
SECTOR FLS 2A
https://ais.avinor.no/no/AIP/View/133/2024-09-05-AIRAC/graphics/449309.pdf
SECTOR ELMEG 2A, SECTOR ELMEG 2B
https://ais.avinor.no/no/AIP/View/133/2024-09-05-AIRAC/graphics/457980.pdf

Will these be added to the sector file?

**Comment by Adrian2k** [comment]
Info I have recieved is that these are not in use at ENBR

**Comment by Azchk** [comment]
I see, interesting. But they are still published procedures as far as I can tell?

**Comment by Adrian2k** [comment]
Closing as #484 covers it
