### ISSUE TITLE
Wrong placement of radio transmitter for ENMS_I_TWR?

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#453]
Image below is from when i was logged on as ENMS_I_TWR. Transmitter is placed at Stokka. Unable to read aircraft on the ground.

![image](https://github.com/user-attachments/assets/1671d8e1-e5f8-4f9f-85f9-6f6f343f24c8)

**Comment by Adrian2k** [comment]
![image](https://github.com/user-attachments/assets/7b858905-e014-4f22-afb5-d54daa26c077)
Can confirm

**Comment by Adrian2k** [comment]
![image](https://github.com/user-attachments/assets/ee79983d-62f4-49dc-8205-9f1fff42b24b)
Adjusted now
