### ISSUE TITLE
ENST not added to VATATIS

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#454]
![image](https://github.com/user-attachments/assets/3309598c-a440-48d9-a0b9-acf5ffc582d0)

**Comment by marud94** [comment]
ATIS is not established on Stokka, therefore not in VATATIS

**Comment by Atriusftw** [comment]
In such case the frequency should be removed from the sector files.

**Comment by marud94** [comment]
Not sure how you got it, it's not in our sectorfile according to GNG. 
![Screenshot_20240917_170101_Chrome](https://github.com/user-attachments/assets/22a97def-2d3b-4bff-b3f9-cc277bb74f18)

**Comment by Atriusftw** [comment]
I now see that the Røst ATIS frequency is in my image. Hence, i'm 99.9% part of the problem here. Sorry! :D
