### ISSUE TITLE
Unable to accsept COPX heading requiests

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#456]
![image](https://github.com/user-attachments/assets/a2cd5682-a265-4978-9ad0-b099b920faa5)

**Comment by marud94** [comment]
Nothing happens when clicking on the tag for example, no options there to accept?

**Comment by meltinglava** [comment]
nope

**Comment by morettio** [comment]
![image](https://github.com/user-attachments/assets/bf2049ed-6556-437e-9efb-45d08b197d00)

**Comment by morettio** [comment]
![image](https://github.com/user-attachments/assets/af5387e5-2aeb-4baf-b356-ea2a5508caf7)

**Comment by morettio** [comment]
This was not COPX, but a Handover Proposal. (HOP).
Please see the General Manual for more info.
