### ISSUE TITLE
Suggestion: Add ACTIVE:1 to MVA maps

### ISSUE THREAD

**Issue by Eseem91** [Vatsim-Scandinavia/ENOR-Sectorfile#457]
Adding ACTIVE:1 to all MVA maps in TopSkyMaps.txt 
This will make MVA maps show at the correct zoom level everywhere always, including in proxy windows, which is very useful for ACC top-down in particular. 

Example:
```
AP:MVA ENGM
COLOR:MVA
FOLDER:MVA
ACTIVE:1
ZOOM:9
FONTSIZE:-:1
STYLE:DOT
```

**Comment by morettio** [comment]
ACTIVE:1 Activates the map automatically when the plugin is loaded.
With this line, all maps with ACTIVE:1 will be shown. in other words, all MVA maps in the sectorfile will be displayed. 
MVA maps are displayed on the controller ID.

**Comment by Eseem91** [comment]
Yes, a feature I prefer, and also solves the issue of maps not loading in proxy instances. Top-down showing all maps is not an issue for ACC because your zoom level will generally be more than auto-hide. For APP, it's not an issue to load them because they're only really looking at their own airspace, though for conjoining airspaces like ENBR/ENZV it's a benefit for the controller to know the lower limits in the directly neighbouring airspace (to be fair this might be configured, I have everything active so I wouldn't know which maps are inactive)

**Comment by morettio** [comment]
If some MVA maps aren't showing when logging on to a position then we need to know. The MVA maps are pr def working as intended.  
All Maps can be shown by ALT+right click -> Maps -> MVA.

**Comment by Eseem91** [comment]
But my way is better!

**Comment by Sanderli25** [comment]
I see that MVA is not enabled by ACTIVE:ID (CJI), but in TopSkySettings. I can do some testing locally, perhaps use the GLOBAL setting.

**Comment by morettio** [comment]
this has been tested and found not working as intended.
