### ISSUE TITLE
Vatsca.org/ links for newly created Airport briefings and Pilot briefing

### ISSUE THREAD

**Issue by Azchk** [Vatsim-Scandinavia/ENOR-Sectorfile#460]
Request Vatsca.org/ shortened links for the newly created ENTO and ENCN Airport briefing pages.
Also request a shortened link for the Norway pilot briefing

**Comment by Adrian2k** [comment]
@blt950

**Comment by blt950** [comment]
I ran into some issues creating the urls, I'll need to find out the issue.

Meanwhile could you link me to the ENTO/ENCN and pilot briefing you've in mind @Azchk ? So I'm sure I'm linking the correct briefing

**Comment by Azchk** [comment]
Pilot Briefing/General Recommendations: https://wiki.vatsim-scandinavia.org/books/norwegian-airports-charts/page/general-recommendations
ENCN: https://wiki.vatsim-scandinavia.org/books/norwegian-airports-charts/page/encn-kristiansand-kjevik
ENTO: https://wiki.vatsim-scandinavia.org/books/norwegian-airports-charts/page/ento-torp-sandefjord

**Comment by blt950** [comment]
Pilot Briefing/General Recommendations: https://vatsca.org/norwaypilot
ENCN: https://vatsca.org/ENCN
ENTO: https://vatsca.org/ENTO
