### ISSUE TITLE
Dissatisfying order of .asr  !

### ISSUE THREAD

**Issue by Eseem91** [Vatsim-Scandinavia/ENOR-Sectorfile#463]
![image](https://github.com/user-attachments/assets/37eb30b0-bedc-45f5-800d-a1c61ef42756)

**Comment by Adrian2k** [comment]
Agreed but it was done intentionally.
ENTO ground map was made after we started defining hotkeys, so it was assigned an empty one to avoid complaints from people used to the existing ones.

**Comment by Adrian2k** [comment]
Brought up for vote in discord to see controllers preference on this
https://discord.com/channels/182554696559362048/1138507455031156796/1301507411370053663

**Comment by Adrian2k** [comment]
Ordering changes, ENTO now on F6
