### ISSUE TITLE
Add "radar" in ENOB airspace

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#467]
@BlomsenSr see internal communication

**Comment by Adrian2k** [comment]
Fixed

**Comment by janfelhut04** [comment]
Any chance to make the radius for the radars at Svallbard and Bjørnøya? From Eurocontrol the ADS radar coverage are shown here. Just a minor change if its possible. https://www.eurocontrol.int/service/automatic-dependent-surveillance-broadcast
