### ISSUE TITLE
Add a keybinds for topskymaps

### ISSUE THREAD

**Issue by janfelhut04** [Vatsim-Scandinavia/ENOR-Sectorfile#468]
I've seen it is possible to add keybinds for topsky maps. Is it possible to add keybinds for MVA maybe others as well. 

Here would be a code example to toggle ENGM MVA with ALT + M. 

Shortcut_RadarMenu_Combo=0x00
Shortcut_Map_Xfr_Key=1,0x4D ; M
Shortcut_Map_Target=1,MVA\MVA ENGM

This could be very helpfull if we only need the MVA at a specific moment. 
I would suggest creating a new topsky_map with all MVAs in Norwy and use this when toggling

**Comment by janfelhut04** [comment]
The codes are placed in TopskySettings and get all the data from TopskyMaps

**Comment by morettio** [comment]
I've tested it and was thinking of doing something like that on other maps. I don't see why we need it on MVA maps since the zoom setting is already implemented. Many think that opening the radar menu and going to maps is too many clicks, and few remember all the shortcuts if we add more of them.

**Comment by janfelhut04** [comment]
Is it at least possible to remove MVA apparance for TWRs? I don't see the reason why we should show MVA for TWR positions. This could be add manually in my opinion.  Showing the VFR reporting points as TWR is more than enough. 
![Skjermbilde 2024-10-11 161731](https://github.com/user-attachments/assets/b872e875-c9a3-4f7f-b854-1e0b6eb56849)

**Comment by morettio** [comment]
I have tested it, and the best solution is adding some lines to the TopSkySettingLocal.txt file.

If we are going to hide it to all _TWR we also need to add it to all XXXX_Y_TWR/GND/DEL and so on. So the best solution to the sectorfile is as it is now.

![image](https://github.com/user-attachments/assets/639a65d4-86f9-4c3e-9b74-04fcad894c36)

**Comment by morettio** [comment]
this is because Topsky reads the setting.txt file first and then the localsettings.txt file after.

**Comment by morettio** [comment]
- [ ] Check if the developer has a solution on the plugins forum
- [ ] Add MVA maps on shortcut
- [ ] Add Cord Fixes shortcut

**Comment by morettio** [comment]
Added Toggle all MVA maps with ALT + M
