### ISSUE TITLE
ENBR CAT H RNPs in STAR list

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#471]
Creating this issue from the discussion on Discord to track it.

The CAT H RNPs on Flesland are missing in the STAR list, namely RNP 043 and RNP 139.

A blocker is that we can't use numbers in the procedures with the current sector file provider.
Alternatives could be discussed here. My suggestion is to use the transitions as prefix to identify them. Example:

RNP043:
`ELMEG · RNP`
`VIKSO · RNP`

RNP139:
`VENIN  · RNP`

**Comment by Dekuistic** [comment]
I believe the suggestion in the origin post is a very good solution given our circumstances, and blockers, however just to vairy it up a little l'll give my input :)

A suggestion is that we can give it a prefix that makes sense, for example RNP H RWY 35/17, or RNP R RWY 35/17 (Stands for Helicopter/Rotorcraft) M;aybe K for Kopter, V for Vertical, etc.
The downside i see with this is that controllers might be accident clear the aircraft for an "RNP H" Instead of RNP 043/139. Though i believe this is destined to happen no matter what we call it.

**Comment by Azchk** [comment]
I would go with Marius's suggestion. It's benificial to limit the use of symbols not in direct relation to the approach. Runway numbers should also not be used (e.g. RNP 17 H and RNP 35 H) as these are not an approaches to a runway, but to a point in space (PinS).

**Comment by Adrian2k** [comment]
I always tried adding these as APP inside GNG - someone suggested adding them as a STAR entry instead which give a optimal solution

```
STAR:ENBR:35:ELMEG·RNP043:ELMEG BR711 BR710 ;  Combiner=ENBR2/12 | ID=35_ELMEG_RNP043
STAR:ENBR:35:VIKSO·RNP043:VIKSO MOMUX BR711 BR710 ;  Combiner=ENBR2/12 | ID=35_VIKSO_RNP043
```

**Comment by Adrian2k** [comment]
`STAR:ENBR:17:VENIN·RNP139:VENIN BR812 BR810 ;  Combiner=ENBR2/12 | ID=17_VENIN_RNP139
`

**Comment by Azchk** [comment]
I would go with Marius's suggestion. It's benificial to limit the use of symbols not in direct relation to the approach. Runway numbers should also not be used (e.g. RNP 17 H and RNP 35 H) as these are not an approaches to a runway, but to a point in space (PinS).

**Comment by Azchk** [comment]
Does this combine with OXEBU/ELMEG STARs, or will it overwrite it?

**Comment by Atriusftw** [comment]
> Does this combine with OXEBU/ELMEG STARs, or will it overwrite it?

It is only possible to select one STAR from the list, so one would have to switch at some point if the pilot follows the entire OBEXU STAR. This is however normal with other approaches as well, as the same field is used to assign approach.

Example: 
![348388403-4bf59fed-47c9-461d-941e-822274f659e5](https://github.com/user-attachments/assets/d89b7fa4-0c85-48a4-bc52-60691a98ab7b)
