### ISSUE TITLE
Wrong handoff freq

### ISSUE THREAD

**Issue by HugoAmdal** [Vatsim-Scandinavia/ENOR-Sectorfile#475]
When controlling BR tower it suggest to hand off to controllers that is controlling along the route of the pilot but doesnt actually cover BR area
One suggesting to hand off to ENOS and one to Copenhagen
![bilde](https://github.com/user-attachments/assets/473e8307-71c0-477a-8db9-5a637a770048)
![bilde](https://github.com/user-attachments/assets/dd4745eb-2a61-4430-91b1-3c3af79933f7)

**Comment by Adrian2k** [comment]
Did you mess with this area? 
![image](https://github.com/user-attachments/assets/9813114c-12f6-4eb2-8358-00149bd51b75)


There is no reason for this to happen unless you activated some airspace which you are not supposed to be owning.
I can not debug anything with the limited information I have here - full screenshots of the scope is more useful than this.

**Comment by Adrian2k** [comment]
Cant see anything related to the sectorfile that will cause this - must be a Euroscope thing.
Closing as wontfix
