### ISSUE TITLE
Mil areas not displayed

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#476]
# X1
![image](https://github.com/user-attachments/assets/b04916dd-f61f-41a4-a316-36be5c572df6)

# X4
![image](https://github.com/user-attachments/assets/e4cc6be3-f274-4a53-b066-325727757406)

**Comment by Adrian2k** [comment]
DANGER AREA END634Z (X4) ACTIVATED FOR MIL ACTIVITY. MIL EXER ALSO
BLW ACTIVE AMA
LOWER: GND UPPER: FL400
FROM: Fri 25 Oct 2024 08:00 TO: Fri 25 Oct 2024 21:00
: NOTAM A/5806/24

DANGER AREA END631Z (X1) ACTIVATED FOR MIL ACTIVITY. MIL EXER ALSO
BLW ACTIVE AMA
LOWER: FL050 UPPER: FL400
FROM: Fri 25 Oct 2024 08:00 TO: Fri 25 Oct 2024 21:00
: NOTAM A/5803/24

**Comment by BlomsenSr** [comment]
Not necessarily anything wrong there. As it is dager areas 631Z and 634Z that are activated, not 631 and 634 shown in the list.

The Zulus are the bounding boxes supposed to be used for atm systems to give warnings before entering the area.

**Comment by morettio** [comment]
Fixed after finding typo error.
Topsky was looking after END634Z, in areas.txt file it was END634 Z.
