### ISSUE TITLE
Topsky 25b14

### ISSUE THREAD

**Issue by morettio** [Vatsim-Scandinavia/ENOR-Sectorfile#477]
- Maps data file syntax updated (coord_pbd, coord_pd, coord_turn, coord_circle added, circle removed)

- Shortcut key can now be set up to toggle all maps within a specified folder

- Settings added to adjust DCL Window default values

- SID/STAR acknowledgement possible also for untracked aircraft, but only when the procedure name is found in the FPL route (not available to acknowledge automatic assignments by EuroScope). Settings for SID and STAR acknowledgement separated, it's now possible to enable the "unacknowledged" coloring for just one of the two.

- Workaround added to force background refresh when area/map activations change (EuroScope bug in versions 3.2.7-3.2.9)

**Comment by Adrian2k** [comment]
@morettio AIRAC day today - is this version already uploaded on github? If so, ready for release?

**Comment by morettio** [comment]
Go for release

*Jakob Arne Brønstad*

*Tlf: (+47) 986 50 540*


tor. 31. okt. 2024 kl. 16:45 skrev Adrian Bjerke ***@***.***>:
