### ISSUE TITLE
Fly and see Santa 2024

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#485]
Same procedure as last year? @krislarsen 

Next AIRAC is 28th Nov, so preferably the FSS changes should be included in this one - if not then there has to be a sub-release closer to FSS.

**Last year:**
```
ENTC:
NIGEX DCT BDO Z200 BARVI

EFRO-ENTC: 
IBSAN Y75 EVIMI DCT GAPRO DCT KIIKA 

ENGM-ENTC:
RIBBE Z125 SOMUB Z103 NIGEX DCT BDO Z200 BARVI

ENTC-EFRO:
ERPUG DCT GOMAV DCT EXUTI DCT GITEV Y86 OSLIT

ENTC-ESNQ:
MOKAX DCT POBEL DCT LAPLA

EFRO:
BEREP Z107 FLS Z286 OSMUM  SOLKA  OSS  BEGDO  BESLA  MISMO  NEMGU 
ALOTI T400 EGAGO  OSLAV  BEGDO  BESLA M607 MISMO  NEMGU
 NIVUN P5 ZOL T400 EGAGO  OSLAV  BEGDO  BESLA  MISMO  NEMGU
(Entry DANKO) INBOB M604 SVA M609 ULMUG M125 ELVOM  ROGED  GEVRU  SUN  ELBOG  BESLA  MISMO  NEMGU
```

**Comment by Adrian2k** [comment]
As discussed internally - there are some minor changes regarding the EFRO routes, however no major changes expected.

**Comment by Adrian2k** [comment]
- [ ] Add ENTC_DEL (remember logon profile + ground area)
- [ ] Add mandatory route displays
- [ ] Fix aliases
- [ ] Holding displays

**Comment by Adrian2k** [comment]
@marud94 @krislarsen do we need to adjust CDM settings at ENTC for the event?

**Comment by krislarsen** [comment]
> @marud94 @krislarsen do we need to adjust CDM settings at ENTC for the event?

Adjusted to 20, witch was maximum last year.

**Comment by krislarsen** [comment]
> * [ ]  Fix aliases
 CC: @marud94 

Adjusted aliases:

> .bnn ENTER BNN (VOR) HOLDING. INBOUND COURSE 020 DEGREES. 1 MIN 30 SEC LEGS. LEFT TURNS
> 
> .aloti ATC HAS ISSUED AN AMENDMENT TO YOUR ROUTE TO EFRO. NEW ROUTE: ALOTI T400 EGAGO DCT OSLAV DCT BEGDO DCT BESLA M607 MISMO DCT NEMGU
> .berep ATC HAS ISSUED AN AMENDMENT TO YOUR ROUTE TO EFRO. NEW ROUTE: BEREP DCT KEKOD DCT OSMUM DCT SOLKA DCT OSS DCT BEGDO DCT BESLA DCT MISMO DCT NEMGU
> .nivun ATC HAS ISSUED AN AMENDMENT TO YOUR ROUTE TO EFRO. NEW ROUTE: NIVUN P5 ZOL T400 EGAGO DCT OSLAV DCT BEGDO DCT BESLA M607 MISMO DCT NEMGU
> .danko ATC HAS ISSUED AN AMENDMENT TO YOUR ROUTE TO EFRO. NEW ROUTE: DANKO M604 SVA M609 ULMUG DCT ELVOM DCT ROGED DCT GEVRU DCT SUN DCT ELBOG DCT BESLA DCT MISMO DCT NEMGU
> .ipton ATC HAS ISSUED AN AMENDMENT TO YOUR ROUTE TO EFRO. NEW ROUTE: IPTON DCT EVLED DCT OSMUM DCT SOLKA DCT OSS DCT BEGDO DCT BESLA DCT MISMO DCT NEMGU

I could not find if we documented the aliases for FSS-specific aliases. Should we do it?

**Comment by marud94** [comment]
> 
> I could not find if we documented the aliases for FSS-specific aliases. Should we do it? CC: @marud94

I have it on the old Google docs alias document. I believe we’ve had it several years as well. Doesn’t take much time to fix so I can update and send it to you to be included in briefing docs for example?

**Comment by krislarsen** [comment]
**2024 Routes**
```
ENTC:
~~ NIGEX DCT BDO Z200 BARVI~~ 
BNN DCT BDO Z200 BARVI

EFRO-ENTC: 
IBSAN Y75 EVIMI DCT GAPRO DCT KIIKA 

ENGM-ENTC:
RIBBE Z125 SOMUB Z103 NIGEX DCT BDO Z200 BARVI

ENTC-EFRO:
ERPUG DCT GOMAV DCT EXUTI DCT GITEV Y86 OSLIT

ENTC-ESNQ:
MOKAX DCT POBEL DCT LAPLA

EFRO:
IPTON DCT EVLED DCT OSMUM DCT SOLKA DCT OSS DCT BEGDO DCT BESLA DCT MISMO DCT NEMGU
~~ BEREP Z107 FLS Z286 OSMUM  SOLKA  OSS  BEGDO  BESLA  MISMO  NEMGU ~~ BEREP DCT KEKOD DCT OSMUM DCT SOLKA DCT OSS DCT BEGDO DCT BESLA DCT MISMO DCT NEMGU
ALOTI T400 EGAGO  OSLAV  BEGDO  BESLA M607 MISMO  NEMGU
NIVUN P5 ZOL T400 EGAGO  OSLAV  BEGDO  BESLA  MISMO  NEMGU
~~(Entry DANKO) INBOB M604 SVA M609 ULMUG M125 ELVOM  ROGED  GEVRU  SUN  ELBOG  BESLA  MISMO  NEMGU~~
DANKO M604 SVA M609 ULMUG DCT ELVOM DCT ROGED DCT GEVRU DCT SUN DCT ELBOG DCT BESLA DCT MISMO DCT NEMGU
```

**Comment by Adrian2k** [comment]
>ENGM-ENTC:
RIBBE Z125 SOMUB Z103 NIGEX DCT BDO Z200 BARVI

This is the published route: RIBBE Z125 SOMUB Z103 BNN DCT BDO Z200 BARVI

**Comment by Adrian2k** [comment]
Have to remove .adopi - it conflicts with .adopi alias for ENGM.
Highly doubt we will need any enroute holding for EFRO so not bothering replacing it
