### ISSUE TITLE
Invalid line R/D Areas

### ISSUE THREAD

**Issue by Sanderli25** [Vatsim-Scandinavia/ENOR-Sectorfile#490]
COORD_ has been added in front of R/D areas with "CIRCLE". Do not know when this happend, or if it has happend to other maps as well:
![image](https://github.com/user-attachments/assets/6a846781-075c-4230-8c95-30de54eb545d)

**Comment by Adrian2k** [comment]
Its related to an recent topsky update #477 - changed last week
![image](https://github.com/user-attachments/assets/d831a070-20a5-4d4b-baaf-0639ad1aab58)

**Comment by Adrian2k** [comment]
Was done in commit 25d136c

Make sure you update the plugins as described in the wiki

**Comment by Sanderli25** [comment]
My bad!
