### ISSUE TITLE
ENEV Helicopter VFR points

### ISSUE THREAD

**Issue by Azchk** [Vatsim-Scandinavia/ENOR-Sectorfile#492]
![image](https://github.com/user-attachments/assets/13a469d3-2121-4804-b419-42c4303e2405)
https://ais.avinor.no/en/AIP/View/134/2024-10-31-AIRAC/graphics/457958.pdf

**Comment by Adrian2k** [comment]
Well.. Because avinor dosent provide coordinates for them

And.. who flies helicopter at ENEV

**Comment by Adrian2k** [comment]
Provide the coordinates (or submit a PR) and I can add it.

**Comment by Azchk** [comment]
N - N068.31.54.000	E016.42.13.000

E - N068.29.33.000	E016.46.46.000

S - N068.27.21.000	E016.43.01.000

W - N068.27.35.000 E016.37.20.000

NW - N068.32.04.000 E016.37.29.000

From Navigraph
