### ISSUE TITLE
Wrong stand info in ES ENTC

### ISSUE THREAD

**Issue by einarstark** [Vatsim-Scandinavia/ENOR-Sectorfile#497]
Stands from IRL/scenerys for ENTC dos not match in ES. See screenshots.
![IRL eAIP Norway](https://github.com/user-attachments/assets/3fbcc848-d92d-4a74-9e83-809a84a4f73d)
![ES ENTC](https://github.com/user-attachments/assets/7848fcc7-e762-432b-af55-3c96e8caf756)

**Comment by Adrian2k** [comment]
![image](https://github.com/user-attachments/assets/1259b12a-b9ee-44c3-bba8-60f8ba924a00)
