### ISSUE TITLE
S3 -> ENGM-DD not next sector

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#499]
Probably unable to do anything about this, but when sitting ENGM_D_APP rwy 01, I was unable to coordinate anything with S3 as I was not next controller.

Worked without any issues on S5 via RIPAM

**Comment by Adrian2k** [comment]
Added as guest in ENGM-E upper airspace - needs testing.

**Comment by krislarsen** [comment]
Adjusted sortorder also to see if it helps.

**Comment by Adrian2k** [comment]
Will close for now - issue can be reopened if issue still remains
