### ISSUE TITLE
Voice ATIS pronounces VOR approach as "war approach" and not "Vee Oh aR approach"

### ISSUE THREAD

**Issue by Azchk** [Vatsim-Scandinavia/ENOR-Sectorfile#501]
![image](https://github.com/user-attachments/assets/682d8b15-7d9a-4722-a9a0-ccec5eff966d)
Pronounces "war/vore"

![image](https://github.com/user-attachments/assets/0cdb8df5-8fca-425c-958a-4dd297c165b3)
Pronounces correctly

**Comment by Adrian2k** [comment]
This is rather an VATSIM issue unfortunately - not something we control.
I sent a message in the AFV facility engineers chat, but I do not have any big hopes of anyone stepping up to fix it.

**Comment by Adrian2k** [comment]
![image](https://github.com/user-attachments/assets/7da0e172-3f2b-4b98-83eb-d664191af4b3)
