### ISSUE TITLE
ESOS freq on radar display for ENVA APP

### ISSUE THREAD

**Issue by marud94** [Vatsim-Scandinavia/ENOR-Sectorfile#504]
According to SOP, ENVA APP can handoff to ESOS when ENBD is offline. Maybe we also can add the ESOS freq on radar display there as we have for ENGM APP and ESOS/ESMM?

**Comment by Adrian2k** [comment]
Perhaps a note that its only if ENBD is offline

**Comment by morettio** [comment]
Added to main, Should only be active if 18R or 25R are not active.
Please test :)
