### ISSUE TITLE
FLO showing FLØ instead of FLO VOR

### ISSUE THREAD

**Issue by Lassssse** [Vatsim-Scandinavia/ENOR-Sectorfile#506]
Had a weird incident today with the FLØ reporting point at ENAL being displayed on a route instead of the FLO (Florø) VOR. However, .find FLO gave me the FLO VOR. Believe I have seen the FLO VOR being displayed earlier (possibly before the newest update, not quite sure.)

**Comment by Adrian2k** [comment]
Its apart of the AIRAC data unfortunatly - cant fix
