### ISSUE TITLE
Release line EKDK -> ENOR og ENOR -> EKDK missing from Topsky Maps Release lines

### ISSUE THREAD

**Issue by Lassssse** [Vatsim-Scandinavia/ENOR-Sectorfile#515]
Would be nice if these also activated automatically when logging onto ENSV/ENOS/ENOR just like the ENOS-ENBD release line. Perchance the other ENOS release lines could also be added here?

**Comment by Adrian2k** [comment]
Release lines from EKDK -> ENOR is always active, no need for automatic activation.

Releaseline from ENOR -> EKDK will not have automatic dispaly on, as we only automatically display releaselines from other sectors to own sector, not vise verca. The display line is available for manual activation
