### ISSUE TITLE
Suggestion: AFIS Tagfamily

### ISSUE THREAD

**Issue by vegsor** [Vatsim-Scandinavia/ENOR-Sectorfile#516]
Euroscope:
![image](https://github.com/user-attachments/assets/ca52f7f8-246d-483c-9346-685011778b4e)
Real Life:
![image](https://github.com/user-attachments/assets/5e13e431-da3d-442a-9ef6-e83290d06a02)
![image](https://github.com/user-attachments/assets/8894e32d-f38f-4a60-b816-59de8c4c7b30)

The tags used by afis at the Bodø RTC

**Comment by Atriusftw** [comment]
Did some cleanup in OP as the relevant code has been submitted as a PR instead. I don't see any problems with adding such a tag for use with AFIS stations that has access to radar, as long as the reference images can be verified.

**Comment by vegsor** [comment]
https://youtu.be/yiBnKY88cOM?si=nIdt0Dn_IVSq4n0b

See 1 min 26 seconds.

Promotional video by avinor

**Comment by Adrian2k** [comment]
Spoke with Simon and it looks ok - however the current tag is a "overflight" tag.
He will double check how the ARR/DEP tags looks like.

Last line is a S-mode readout info, not supported in ES - but assigned altitude and assigned speed could probably take its place.

You never wrote how the tag is built up, but with confirmation from Simon this is the content:
Tag owner
Callsign - Aircraft type
Current altitude - Ground speed
STAR - DEST
S-mode readout

**Comment by krislarsen** [comment]
> Is it necessary to have assigned speed/altitude field? Should not be relevant to AFIS officer. These can also be edited in the sector list. Then the label is very simple, and will display same information regardless of untagged/tagged/detailed

I think that should not be necessary. Alternately, we can make it possible to amend assign altitude/speed by left or right click on current speed and altitude value. I'll let it up to you
