### ISSUE TITLE
Add custom ATIS parameter for de-ice

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#518]
Suggest using parameter `&deice` with the following string: `ADVISE IF DE-ICE IS REQUIRED ON FIRST CONTACT WITH ATC`

**Comment by marud94** [comment]
For now it is manually entered and always on. Having some difficulties getting liquid to echo the statement for &deice. Needs more investigating with #325

**Comment by Adrian2k** [comment]
Done - added with custom variable `&advdeice=`

**Comment by Atriusftw** [comment]
Nitpicking: Can you change "advice" to "advise", which is the correct form please? (=

**Comment by marud94** [comment]
@Atriusftw fixed.
