### ISSUE TITLE
[BUG] OTHER SID missing on ENTC

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#519]
**Screenshots**
![image](https://github.com/user-attachments/assets/af767f84-21e8-46c4-a1aa-f0da1b6cadc8)
![image](https://github.com/user-attachments/assets/862ce8d2-3088-49cb-836b-65a15c32add8)

**Describe the bug**
No `OTHER` SID to use for visual climb etc. Applies to both runways.

**Expected behavior**
Having a `OTHER` SID :)

**Additional context**
N/A

**Comment by Adrian2k** [comment]
This must be quite a old bug
Surprised no one has reported it yet.

Anyways fixed now for next release:

```
SID:ENTC:18:ENTC3B:ENTC ; Combiner=ENTC2/2 | ID=18_ENTC3B
SID:ENTC:18:OTHER:ENTC ; Combiner=ENTC2/1 | ID=18_OTHER
SID:ENTC:18:VECTORS:ENTC ; Combiner=ENTC2/1 | ID=18_VECTORS
SID:ENTC:18:VFR:ENTC ; Combiner=ENTC2/1 | ID=18_VFR
SID:ENTC:36:ENTC2A:ENTC ; Combiner=ENTC2/2 | ID=36_ENTC2A
SID:ENTC:36:LOMVI6X:KV LOMVI ; Combiner=ENTC2/2 | ID=36_LOMV6X
SID:ENTC:36:OTHER:ENTC ; Combiner=ENTC2/1 | ID=36_OTHER
SID:ENTC:36:VECTORS:ENTC ; Combiner=ENTC2/1 | ID=36_VECTORS
SID:ENTC:36:VFR:ENTC ; Combiner=ENTC2/1 | ID=36_VFR
```
