### ISSUE TITLE
[OTHER] Sector ownership for ENML with TMA split

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/ENOR-Sectorfile#529]
Who is the correct owner of ENML with TMA Split?

In our sector files it's set to ENAL_APP
![image](https://github.com/user-attachments/assets/fc1693f1-eaf4-49da-96be-187bbfbb7606)

According to Vatglasses, it's owned by ENKB_APP.
![image](https://github.com/user-attachments/assets/39d61082-e545-4236-8c8c-ef65d7e8de50)

**Comment by Adrian2k** [comment]
Time to implement a new rule then - no Møre splitting without Molde information!

**Comment by Adrian2k** [comment]
Amended the ownership setup in our sectorfile now

```
ENML_I_TWR
ENKB_APP
ENAL_APP
ENRC_N_CTR
ENBD_S_CTR
ENBD_C_CTR
ENBD_CTR
ENOR_SC_CTR
ENOR_CTR
```
