### ISSUE TITLE
ES Discord Plugin compability with newest EuroScope version

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#57]
Someone has reported that it casues crashes with the newest Euroscope Beta.

To be tested.

**Comment by Adrian2k** [comment]
Can't reproduce yet.
Might have something with towerview to do.

**Comment by morettio** [comment]
Same here.

**Comment by Adrian2k** [comment]
Will unload the plugin in the sectorfile. Those who want this plugin loaded should load it manually.
