### ISSUE TITLE
ENBR COPX

### ISSUE THREAD

**Issue by morettio** [Vatsim-Scandinavia/ENOR-Sectorfile#59]
ENBR FL copex Nidgi STAR FL170
Satt ENSV_CTR

**Comment by krislarsen** [comment]
Sliter litt med å reprodusere denne COPXen. Ligger 3 ulike COPXer med NIDGI som COPX fix. Setter denne på vent intil det kommer en ny feilmelding som kan dokumentere i større grad hvor flyet kommer fra osv.

**Comment by krislarsen** [comment]
Har ikke hørt noe om dette siden, så stenger i mellomtiden
