### ISSUE TITLE
reports uncontrolled when ENOR_S is online

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#71]
![image](https://user-images.githubusercontent.com/17087998/185999004-441f5e33-eec4-4cea-b3ce-e4717c225f9c.png)
Unattended aerodrome procedures apply on 122.8 but polaris is online.

**Comment by marud94** [comment]
The airport needs an active ATIS to show as controlled through VATATIS.

**Comment by meltinglava** [comment]
But cant we instead show this as controllers online. They do parse the vatsim api so they know who are online.

**Comment by marud94** [comment]
> But cant we instead show this as controllers online. They do parse the vatsim api so they know who are online.

It is not us that code this part. It only checks online stations when a URL is active on the network if I understand correctly. It is the developers intention to make ATISes more permanent, but that is far off in the future and under discussions with VATSIM.
