### ISSUE TITLE
New Reykjavik sectorisation

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#72]
Reykjavik will change their sectorisation setup in the upcomming AIRAC.
This requires some changes within TopSky that displays the sector frequencies.

BIRD_1_CTR -> BIRD_S1_CTR
BIRD_2_CTR -> BIRD_S2_CTR
BIRD_3_CTR -> BIRD_S3_CTR

BIRD_4_CTR -> BIRD_E1_CTR 
BIRD_5_CTR -> BIRD_E2_CTR (new freq 132.200)
New station: BIRD_E2_CTR (frequency currently in conflict with ENOR_CTR)
New station: BIRD_N1_CTR (133.100)

S1
S2
S3
E1
E2
E3

CC1
CC2
CC3

Sectorisation of East sector (note new level splits, previously only one split excisted):
![image](https://user-images.githubusercontent.com/35482228/186417683-80736ab5-ba28-4a70-86f2-9f97d023851f.png)

For the north sector, this is now the following
BICC_2_FSS
BICC_1_FSS
BICC_3_FSS

![image](https://user-images.githubusercontent.com/59777657/186687245-d5debf71-ac17-4ba5-91df-ae2daf0786b0.png)
![image](https://user-images.githubusercontent.com/59777657/186690981-8c5259fe-1410-4c6a-a79c-c8587769fc0b.png)

**Comment by Adrian2k** [comment]
There might be some small adjustments to the proposed levels.

**Comment by morettio** [comment]
S1
S2
S3
E1
E2
E3

CC1
CC2
CC3

![image](https://user-images.githubusercontent.com/59777657/186687111-30600b34-8140-4f31-a6c8-0f126ee83766.png)

**Comment by Adrian2k** [comment]
![image](https://user-images.githubusercontent.com/35482228/186690830-3ecd0d3a-bb9a-44bf-8ada-81cec61489b2.png)

**Comment by morettio** [comment]
Waiting on correct freq on E3 and update from GNG.

**Comment by Adrian2k** [comment]
E3 freq 128.8

**Comment by Adrian2k** [comment]
Changes are done in GNG.
Splits adjusted to the following levels:
![image](https://user-images.githubusercontent.com/35482228/187497926-4c64d5a0-1211-4726-8bd5-90138ae79cb7.png)

**Comment by morettio** [comment]
Need Island to update sectors in GNG for testing.

**Comment by morettio** [comment]
Tror dette blir greit

![image](https://user-images.githubusercontent.com/59777657/188691621-cd9a32ac-f62b-4e12-a180-1fd2f3c05bb4.png)

![image](https://user-images.githubusercontent.com/59777657/188691749-8629d95e-d6ce-4ff5-af6d-a884ae758d98.png)

![image](https://user-images.githubusercontent.com/59777657/188691850-9a4f041a-e6c3-4e66-8930-9b22a5db8dab.png)

**Comment by morettio** [comment]
Active in A2209
