### ISSUE TITLE
COPX ENBR arrival via S8

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#74]
ENBR arrival via S8 is recciving XFL FL320 to S13, should be RFL XFL

**Comment by marud94** [comment]
@krislarsen Nye greier? Ser at COPX er definert for at ENOS til ENSV kan gi descend 320 hvis flyet er over 325. Flesland ligger inne i den mixen der.

> Oslo may clear traffic via sector 5/6 with destination within Stavanger and cruising level above
> FL325 for descend to FL320.

**Comment by krislarsen** [comment]
> @krislarsen Nye greier? Ser at COPX er definert for at ENOS til ENSV kan gi descend 320 hvis flyet er over 325. Flesland ligger inne i den mixen der.
> 
> > Oslo may clear traffic via sector 5/6 with destination within Stavanger and cruising level above
> > FL325 for descend to FL320.

Denne feilmeldingen  gjelder S8. Det du refererer til er dersom trafikken kommer fra S5 eller S6

**Comment by marud94** [comment]
Du har en COPX inne som er merket likt på S8 som jeg så hvertfall (om jeg
så rett). Så i så fall kan det være at den må fjernes bare.

fre. 9. des. 2022, 23:25 skrev krislarsen ***@***.***>:

**Comment by krislarsen** [comment]
Trolig må se gjennom hele COPX-greiene på nytt. Men klarer ikke å gjenskape denne. Stenger denne midlertidig
