### ISSUE TITLE
Sectorline BICC_3_FSS

### ISSUE THREAD

**Issue by morettio** [Vatsim-Scandinavia/ENOR-Sectorfile#79]
Sectorline BICC_3_FSS to ENOB not showing

![image](https://user-images.githubusercontent.com/59777657/188722077-d26d488f-16a5-4616-a45c-1d069a2b3e57.png)

**Comment by Adrian2k** [comment]
![image](https://user-images.githubusercontent.com/35482228/191962563-d3243948-470e-4772-81fc-0893ccb1874a.png)

BICC_3 is not assigned any sectors. Only BICC_2 and BICC_1 borders to us in that order.
