### ISSUE TITLE
Update controller info to include vatglasses

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#83]
Now that vatglasses are available in Norway, we no longer need to poorly describe where we cover in the controller info.
The link for vatglasses can now be provided instead.

**Comment by krislarsen** [comment]
Is this added? Looks like the logonprofiles in Git is not added to the sectorfile in GNG

**Comment by Adrian2k** [comment]
Uploaded to GNG
