### ISSUE TITLE
Topsky menu MAPS -> LOA -> ENOR -> EKDK LOKSA(EKBI) point in EFIN

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/ENOR-Sectorfile#87]
![image](https://user-images.githubusercontent.com/17087998/190460341-bf418ef1-7817-478d-b8c5-821f9b726edc.png)

**Comment by Adrian2k** [comment]
Tror kanskje LOKSA ligger duplicate i navdata (en i Finland og en i Danmark).
Kan evnt løses med å definere punktet med koordinater istedenfor FIX.

**Comment by morettio** [comment]
Skal legge det inn som koordinat

**Comment by morettio** [comment]
Added to MAIN
