### ISSUE TITLE
Adjust metar list position

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#95]
Når vind vises med G så forsvinner QNH ut av vinduet fordi det er plassert helt mot høyre kant og er kun tilpasset når det ikke er gust vist i metarlist. Kan vi flytte denne litt til venstre?

**Comment by Adrian2k** [comment]
Jeg har 1440p skjerm og ingen referanse til 1080 skjerm. Noen andre må eventuelt løse denne.
