### ISSUE TITLE
Implementation of CDM?

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#97]
https://cdm.vatsimspain.es/

I do not currently have time to look too much into it.

CDM can be useful during events and does also talk with ECFMP.
Currently, we have not gotten any ECFMP restrictions and rarely have traffic amounts that warrant this, but it can be nice to have for bigger events that also include flow restrictions.

I have started a spreadsheet for ENGM with expected taxi out times based on an external source for ENGM, send me a message if interested.

**Comment by marud94** [comment]
![Skjermbilde 2022-10-06 005930](https://user-images.githubusercontent.com/79376555/194179683-043f1579-510e-4dde-bd87-88fd6403e117.png)
![Skjermbilde 2022-10-06 005352](https://user-images.githubusercontent.com/79376555/194179711-3e9f0f5b-0652-4f2d-b1ee-33e398df3d32.png)
![Skjermbilde 2022-10-06 005316](https://user-images.githubusercontent.com/79376555/194179721-2b153492-1d56-4058-ba1d-ed519b21c37a.png)
![Skjermbilde 2022-10-06 005231](https://user-images.githubusercontent.com/79376555/194179729-d41705da-f67c-4f14-af0a-9b3791c33b3f.png)

**Comment by marud94** [comment]
To do:
- [ ] Test the usage of MASTER vs SLAVE. One master and several slaves and also controller change.
- [ ] Review the need for every function the plugin offers. TSAC seems redundant as it controller selected, but automaticly gives TSAT unless changed. 
- [ ] Test with ECFMP flow measure
- [ ] Review operations rate file
- [ ] Make taxi times document. It uses boxes based on coordinates so make separate times for each runway from each part of the apron (domestic north/south, pier north east/west, international north/south, cargo, GA)

**Comment by marud94** [comment]
![image](https://user-images.githubusercontent.com/79376555/194400042-6327f07e-3b92-4dcf-9816-ac7871b16015.png)
With MDI issued through ECFMP. Gives CTOT accordingly and updates TSAT and TTOT.

**Comment by marud94** [comment]
![Skjermbilde 2022-10-06 214854](https://user-images.githubusercontent.com/79376555/194405356-4a992e08-3707-4155-930e-069099782c88.png)
Final departure list for testing. Showing the plugin when setup as master and not having touched any aircraft. P is planned and does not have a TSAT. When changing to C it will assign a TTOT and calculate the TSAT. When changing to I it will remove the TSAT and TTOT as the TSAT is no longer valid and a new TOBT is required. This can be assigned by clicking on TOBT if the pilot is ready for push within 6 minutes.

**Comment by marud94** [comment]
![image](https://user-images.githubusercontent.com/79376555/194412375-bc8bb2ae-d915-4e25-8e13-6c7fd9eaae7e.png)

**Comment by marud94** [comment]
@Adrian2k Har lagt inn foreløpige taxitider, men kan du få oppdatert dokumentet? Trenger primært for 201-208, 171-178, 3-15, 10-28, 60-80, 93-96, 61-89, 36-58, 39-54, 181-188, 311-322, 323-337. Trenger bare en tid pr. intervall.

**Comment by morettio** [comment]
![image](https://user-images.githubusercontent.com/59777657/196033999-e1514f90-0fee-4479-9bbc-6e6daca13554.png)
 Får denne feilen nå om man laster inn CDM i ES. prøvde også å flytte den ut av pluginsmappa, men samme feil da. @krislarsen fikk også samme feil.

**Comment by marud94** [comment]
[CDM Manual.docx](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/files/9794739/CDM.Manual.docx)

@morettio @krislarsen Not updated for v2.11. Should not be much new in 2.11 except auto-updating TOBT after new EOBT.

**Comment by marud94** [comment]
[CDM Manual.docx](https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/files/10036379/CDM.Manual.docx)

**Comment by morettio** [comment]
Nice, We should try to do a Beta on FSS. If it needs more work we can withdraw it after FSS.

**Comment by marud94** [comment]
> Nice, We should try to do a Beta on FSS. If it needs more work we can withdraw it after FSS.

My thoughts too. Will wait until closer in case a New plugin version is released soon

**Comment by Adrian2k** [comment]
> * [ ]  Ask Lange (VATSCA Web) about possibility of having taxirate document on server to prevent tampering by individual clients.

Kan ta det på min webserver, enklere å tildele tilganger der.

**Comment by marud94** [comment]
> > * [ ]   Ask Lange (VATSCA Web) about possibility of having taxirate document on server to prevent tampering by individual clients.
> 
> Kan ta det på min webserver, enklere å tildele tilganger der.

Hadde vært knall. Tenker det går greit nå når vi tester det litt ut, for da får vi se om folk tukler med innstillingene. Blir det behov så fikser vi det fort.

**Comment by marud94** [comment]
![Skjermbilde 2022-12-01 213430](https://user-images.githubusercontent.com/79376555/205154509-cfda0715-419c-4582-b9db-b88046d046d6.png)

**Comment by marud94** [comment]
@Adrian2k Husk å legge CDM til .prf så den autoloader med sektorfil fra start.

**Comment by Adrian2k** [comment]
> > > * [ ]    Ask Lange (VATSCA Web) about possibility of having taxirate document on server to prevent tampering by individual clients.
> > 
> > 
> > Kan ta det på min webserver, enklere å tildele tilganger der.
> 
> Hadde vært knall. Tenker det går greit nå når vi tester det litt ut, for da får vi se om folk tukler med innstillingene. Blir det behov så fikser vi det fort.


@marud94 @morettio 

Dere har fått invite til en github repo dere kan bruke til å hoste filer.
Filene blir automatisk lasta opp til adbj.no/cdm/filnavn

Feks - https://adbj.no/cdm/test.txt

Trenger flere tilgang så kan jeg tildele.
