### ISSUE TITLE
Display RNP O 01R

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/ENOR-Sectorfile#98]
![image](https://user-images.githubusercontent.com/79529337/192345995-46dd5f5c-db0f-4a4c-899d-72772e6077e3.png)

Dette er vel feil :P

**Comment by Adrian2k** [comment]
Det er kjent og ikke mulig for meg å løse da det er autogenerert.

**Comment by Adrian2k** [comment]
Blitt fikset manuelt, men ikke optimal løsning da vi prøver å unngå manuelle entries.
